msrv = "1.88.0"

# for result_large_err
# https://doc.rust-lang.org/clippy/lint_configuration.html#large-error-threshold
large-error-threshold = 256

# for large_enum_variant
# https://doc.rust-lang.org/clippy/lint_configuration.html#enum-variant-size-threshold
enum-variant-size-threshold = 512
