#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
TMP_FILE=$(mktemp /tmp/countryInfo.txt.XXXXXX)

curl "https://download.geonames.org/export/dump/countryInfo.txt" -o ${TMP_FILE}

cd "${SCRIPT_DIR}"

cat << EOF > ../../../lib/g3-geoip/src/country.rs
/*
 * Copyright 2023 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

///
/// This file is auto generated by scripts/generate/country/convert.sh,
/// by using the data from https://download.geonames.org/export/dump/countryInfo.txt
///
use std::str::FromStr;

$(cat ${TMP_FILE} | awk -F'\t' -f iso3166_alpha2_enum.awk)

$(cat ${TMP_FILE} | awk -F'\t' -f iso3166_alpha2_name.awk)

$(cat ${TMP_FILE} | awk -F'\t' -f iso3166_alpha2_from_str.awk)
EOF

rm ${TMP_FILE}

