[package]
name = "g3tiles-ctl"
version = "0.1.0"
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
futures-util.workspace = true
capnp.workspace = true
g3-ctl.workspace = true
g3tiles-proto = { path = "../../proto" }
