apiVersion: v1
kind: ServiceAccount
metadata:
  name: arcus-g3-swg
  labels:
    app: arcus-g3-swg
    component: rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arcus-g3-swg
  labels:
    app: arcus-g3-swg
    component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arcus-g3-swg
  labels:
    app: arcus-g3-swg
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arcus-g3-swg
subjects:
- kind: ServiceAccount
  name: arcus-g3-swg
  namespace: default
