/*
 * Copyright 2023 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

///
/// This file is auto generated by scripts/generate/country/convert.sh,
/// by using the data from https://download.geonames.org/export/dump/countryInfo.txt
///
use std::str::FromStr;

use crate::ContinentCode;

const ALL_COUNTRY_NAMES: &[&str] = &[
    "Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua and Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Angola",
    "Antarctica",
    "Argentina",
    "American Samoa",
    "Austria",
    "Australia",
    "Aruba",
    "Aland Islands",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Saint Barthelemy",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Bonaire, Saint Eustatius and Saba ",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cocos Islands",
    "Democratic Republic of the Congo",
    "Central African Republic",
    "Republic of the Congo",
    "Switzerland",
    "Ivory Coast",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curacao",
    "Christmas Island",
    "Cyprus",
    "Czechia",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Western Sahara",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Micronesia",
    "Faroe Islands",
    "France",
    "Gabon",
    "United Kingdom",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Equatorial Guinea",
    "Greece",
    "South Georgia and the South Sandwich Islands",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hong Kong",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "British Indian Ocean Territory",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "Saint Kitts and Nevis",
    "North Korea",
    "South Korea",
    "Kosovo",
    "Kuwait",
    "Cayman Islands",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "Marshall Islands",
    "North Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Northern Mariana Islands",
    "Martinique",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre and Miquelon",
    "Pitcairn",
    "Puerto Rico",
    "Palestinian Territory",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Reunion",
    "Romania",
    "Serbia",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "South Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena",
    "Slovenia",
    "Svalbard and Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "Sao Tome and Principe",
    "El Salvador",
    "Sint Maarten",
    "Syria",
    "Eswatini",
    "Turks and Caicos Islands",
    "Chad",
    "French Southern Territories",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "Timor Leste",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "United States Minor Outlying Islands",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vatican",
    "Saint Vincent and the Grenadines",
    "Venezuela",
    "British Virgin Islands",
    "U.S. Virgin Islands",
    "Vietnam",
    "Vanuatu",
    "Wallis and Futuna",
    "Samoa",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe",
    "Serbia and Montenegro",
    "Netherlands Antilles",
];

#[derive(Debug, Clone, Copy)]
pub enum ISO3166Alpha2CountryCode {
    AD, /* Andorra */
    AE, /* United Arab Emirates */
    AF, /* Afghanistan */
    AG, /* Antigua and Barbuda */
    AI, /* Anguilla */
    AL, /* Albania */
    AM, /* Armenia */
    AO, /* Angola */
    AQ, /* Antarctica */
    AR, /* Argentina */
    AS, /* American Samoa */
    AT, /* Austria */
    AU, /* Australia */
    AW, /* Aruba */
    AX, /* Aland Islands */
    AZ, /* Azerbaijan */
    BA, /* Bosnia and Herzegovina */
    BB, /* Barbados */
    BD, /* Bangladesh */
    BE, /* Belgium */
    BF, /* Burkina Faso */
    BG, /* Bulgaria */
    BH, /* Bahrain */
    BI, /* Burundi */
    BJ, /* Benin */
    BL, /* Saint Barthelemy */
    BM, /* Bermuda */
    BN, /* Brunei */
    BO, /* Bolivia */
    BQ, /* Bonaire, Saint Eustatius and Saba  */
    BR, /* Brazil */
    BS, /* Bahamas */
    BT, /* Bhutan */
    BV, /* Bouvet Island */
    BW, /* Botswana */
    BY, /* Belarus */
    BZ, /* Belize */
    CA, /* Canada */
    CC, /* Cocos Islands */
    CD, /* Democratic Republic of the Congo */
    CF, /* Central African Republic */
    CG, /* Republic of the Congo */
    CH, /* Switzerland */
    CI, /* Ivory Coast */
    CK, /* Cook Islands */
    CL, /* Chile */
    CM, /* Cameroon */
    CN, /* China */
    CO, /* Colombia */
    CR, /* Costa Rica */
    CU, /* Cuba */
    CV, /* Cabo Verde */
    CW, /* Curacao */
    CX, /* Christmas Island */
    CY, /* Cyprus */
    CZ, /* Czechia */
    DE, /* Germany */
    DJ, /* Djibouti */
    DK, /* Denmark */
    DM, /* Dominica */
    DO, /* Dominican Republic */
    DZ, /* Algeria */
    EC, /* Ecuador */
    EE, /* Estonia */
    EG, /* Egypt */
    EH, /* Western Sahara */
    ER, /* Eritrea */
    ES, /* Spain */
    ET, /* Ethiopia */
    FI, /* Finland */
    FJ, /* Fiji */
    FK, /* Falkland Islands */
    FM, /* Micronesia */
    FO, /* Faroe Islands */
    FR, /* France */
    GA, /* Gabon */
    GB, /* United Kingdom */
    GD, /* Grenada */
    GE, /* Georgia */
    GF, /* French Guiana */
    GG, /* Guernsey */
    GH, /* Ghana */
    GI, /* Gibraltar */
    GL, /* Greenland */
    GM, /* Gambia */
    GN, /* Guinea */
    GP, /* Guadeloupe */
    GQ, /* Equatorial Guinea */
    GR, /* Greece */
    GS, /* South Georgia and the South Sandwich Islands */
    GT, /* Guatemala */
    GU, /* Guam */
    GW, /* Guinea-Bissau */
    GY, /* Guyana */
    HK, /* Hong Kong */
    HM, /* Heard Island and McDonald Islands */
    HN, /* Honduras */
    HR, /* Croatia */
    HT, /* Haiti */
    HU, /* Hungary */
    ID, /* Indonesia */
    IE, /* Ireland */
    IL, /* Israel */
    IM, /* Isle of Man */
    IN, /* India */
    IO, /* British Indian Ocean Territory */
    IQ, /* Iraq */
    IR, /* Iran */
    IS, /* Iceland */
    IT, /* Italy */
    JE, /* Jersey */
    JM, /* Jamaica */
    JO, /* Jordan */
    JP, /* Japan */
    KE, /* Kenya */
    KG, /* Kyrgyzstan */
    KH, /* Cambodia */
    KI, /* Kiribati */
    KM, /* Comoros */
    KN, /* Saint Kitts and Nevis */
    KP, /* North Korea */
    KR, /* South Korea */
    XK, /* Kosovo */
    KW, /* Kuwait */
    KY, /* Cayman Islands */
    KZ, /* Kazakhstan */
    LA, /* Laos */
    LB, /* Lebanon */
    LC, /* Saint Lucia */
    LI, /* Liechtenstein */
    LK, /* Sri Lanka */
    LR, /* Liberia */
    LS, /* Lesotho */
    LT, /* Lithuania */
    LU, /* Luxembourg */
    LV, /* Latvia */
    LY, /* Libya */
    MA, /* Morocco */
    MC, /* Monaco */
    MD, /* Moldova */
    ME, /* Montenegro */
    MF, /* Saint Martin */
    MG, /* Madagascar */
    MH, /* Marshall Islands */
    MK, /* North Macedonia */
    ML, /* Mali */
    MM, /* Myanmar */
    MN, /* Mongolia */
    MO, /* Macao */
    MP, /* Northern Mariana Islands */
    MQ, /* Martinique */
    MR, /* Mauritania */
    MS, /* Montserrat */
    MT, /* Malta */
    MU, /* Mauritius */
    MV, /* Maldives */
    MW, /* Malawi */
    MX, /* Mexico */
    MY, /* Malaysia */
    MZ, /* Mozambique */
    NA, /* Namibia */
    NC, /* New Caledonia */
    NE, /* Niger */
    NF, /* Norfolk Island */
    NG, /* Nigeria */
    NI, /* Nicaragua */
    NL, /* Netherlands */
    NO, /* Norway */
    NP, /* Nepal */
    NR, /* Nauru */
    NU, /* Niue */
    NZ, /* New Zealand */
    OM, /* Oman */
    PA, /* Panama */
    PE, /* Peru */
    PF, /* French Polynesia */
    PG, /* Papua New Guinea */
    PH, /* Philippines */
    PK, /* Pakistan */
    PL, /* Poland */
    PM, /* Saint Pierre and Miquelon */
    PN, /* Pitcairn */
    PR, /* Puerto Rico */
    PS, /* Palestinian Territory */
    PT, /* Portugal */
    PW, /* Palau */
    PY, /* Paraguay */
    QA, /* Qatar */
    RE, /* Reunion */
    RO, /* Romania */
    RS, /* Serbia */
    RU, /* Russia */
    RW, /* Rwanda */
    SA, /* Saudi Arabia */
    SB, /* Solomon Islands */
    SC, /* Seychelles */
    SD, /* Sudan */
    SS, /* South Sudan */
    SE, /* Sweden */
    SG, /* Singapore */
    SH, /* Saint Helena */
    SI, /* Slovenia */
    SJ, /* Svalbard and Jan Mayen */
    SK, /* Slovakia */
    SL, /* Sierra Leone */
    SM, /* San Marino */
    SN, /* Senegal */
    SO, /* Somalia */
    SR, /* Suriname */
    ST, /* Sao Tome and Principe */
    SV, /* El Salvador */
    SX, /* Sint Maarten */
    SY, /* Syria */
    SZ, /* Eswatini */
    TC, /* Turks and Caicos Islands */
    TD, /* Chad */
    TF, /* French Southern Territories */
    TG, /* Togo */
    TH, /* Thailand */
    TJ, /* Tajikistan */
    TK, /* Tokelau */
    TL, /* Timor Leste */
    TM, /* Turkmenistan */
    TN, /* Tunisia */
    TO, /* Tonga */
    TR, /* Turkey */
    TT, /* Trinidad and Tobago */
    TV, /* Tuvalu */
    TW, /* Taiwan */
    TZ, /* Tanzania */
    UA, /* Ukraine */
    UG, /* Uganda */
    UM, /* United States Minor Outlying Islands */
    US, /* United States */
    UY, /* Uruguay */
    UZ, /* Uzbekistan */
    VA, /* Vatican */
    VC, /* Saint Vincent and the Grenadines */
    VE, /* Venezuela */
    VG, /* British Virgin Islands */
    VI, /* U.S. Virgin Islands */
    VN, /* Vietnam */
    VU, /* Vanuatu */
    WF, /* Wallis and Futuna */
    WS, /* Samoa */
    YE, /* Yemen */
    YT, /* Mayotte */
    ZA, /* South Africa */
    ZM, /* Zambia */
    ZW, /* Zimbabwe */
    CS, /* Serbia and Montenegro */
    AN, /* Netherlands Antilles */
}

impl ISO3166Alpha2CountryCode {
    pub fn name(&self) -> &'static str {
        ALL_COUNTRY_NAMES[*self as usize]
    }

    pub fn continent(&self) -> ContinentCode {
        match self {
            ISO3166Alpha2CountryCode::AD => ContinentCode::EU,
            ISO3166Alpha2CountryCode::AE => ContinentCode::AS,
            ISO3166Alpha2CountryCode::AF => ContinentCode::AS,
            ISO3166Alpha2CountryCode::AG => ContinentCode::NA,
            ISO3166Alpha2CountryCode::AI => ContinentCode::NA,
            ISO3166Alpha2CountryCode::AL => ContinentCode::EU,
            ISO3166Alpha2CountryCode::AM => ContinentCode::AS,
            ISO3166Alpha2CountryCode::AO => ContinentCode::AF,
            ISO3166Alpha2CountryCode::AQ => ContinentCode::AN,
            ISO3166Alpha2CountryCode::AR => ContinentCode::SA,
            ISO3166Alpha2CountryCode::AS => ContinentCode::OC,
            ISO3166Alpha2CountryCode::AT => ContinentCode::EU,
            ISO3166Alpha2CountryCode::AU => ContinentCode::OC,
            ISO3166Alpha2CountryCode::AW => ContinentCode::NA,
            ISO3166Alpha2CountryCode::AX => ContinentCode::EU,
            ISO3166Alpha2CountryCode::AZ => ContinentCode::AS,
            ISO3166Alpha2CountryCode::BA => ContinentCode::EU,
            ISO3166Alpha2CountryCode::BB => ContinentCode::NA,
            ISO3166Alpha2CountryCode::BD => ContinentCode::AS,
            ISO3166Alpha2CountryCode::BE => ContinentCode::EU,
            ISO3166Alpha2CountryCode::BF => ContinentCode::AF,
            ISO3166Alpha2CountryCode::BG => ContinentCode::EU,
            ISO3166Alpha2CountryCode::BH => ContinentCode::AS,
            ISO3166Alpha2CountryCode::BI => ContinentCode::AF,
            ISO3166Alpha2CountryCode::BJ => ContinentCode::AF,
            ISO3166Alpha2CountryCode::BL => ContinentCode::NA,
            ISO3166Alpha2CountryCode::BM => ContinentCode::NA,
            ISO3166Alpha2CountryCode::BN => ContinentCode::AS,
            ISO3166Alpha2CountryCode::BO => ContinentCode::SA,
            ISO3166Alpha2CountryCode::BQ => ContinentCode::NA,
            ISO3166Alpha2CountryCode::BR => ContinentCode::SA,
            ISO3166Alpha2CountryCode::BS => ContinentCode::NA,
            ISO3166Alpha2CountryCode::BT => ContinentCode::AS,
            ISO3166Alpha2CountryCode::BV => ContinentCode::AN,
            ISO3166Alpha2CountryCode::BW => ContinentCode::AF,
            ISO3166Alpha2CountryCode::BY => ContinentCode::EU,
            ISO3166Alpha2CountryCode::BZ => ContinentCode::NA,
            ISO3166Alpha2CountryCode::CA => ContinentCode::NA,
            ISO3166Alpha2CountryCode::CC => ContinentCode::AS,
            ISO3166Alpha2CountryCode::CD => ContinentCode::AF,
            ISO3166Alpha2CountryCode::CF => ContinentCode::AF,
            ISO3166Alpha2CountryCode::CG => ContinentCode::AF,
            ISO3166Alpha2CountryCode::CH => ContinentCode::EU,
            ISO3166Alpha2CountryCode::CI => ContinentCode::AF,
            ISO3166Alpha2CountryCode::CK => ContinentCode::OC,
            ISO3166Alpha2CountryCode::CL => ContinentCode::SA,
            ISO3166Alpha2CountryCode::CM => ContinentCode::AF,
            ISO3166Alpha2CountryCode::CN => ContinentCode::AS,
            ISO3166Alpha2CountryCode::CO => ContinentCode::SA,
            ISO3166Alpha2CountryCode::CR => ContinentCode::NA,
            ISO3166Alpha2CountryCode::CU => ContinentCode::NA,
            ISO3166Alpha2CountryCode::CV => ContinentCode::AF,
            ISO3166Alpha2CountryCode::CW => ContinentCode::NA,
            ISO3166Alpha2CountryCode::CX => ContinentCode::OC,
            ISO3166Alpha2CountryCode::CY => ContinentCode::EU,
            ISO3166Alpha2CountryCode::CZ => ContinentCode::EU,
            ISO3166Alpha2CountryCode::DE => ContinentCode::EU,
            ISO3166Alpha2CountryCode::DJ => ContinentCode::AF,
            ISO3166Alpha2CountryCode::DK => ContinentCode::EU,
            ISO3166Alpha2CountryCode::DM => ContinentCode::NA,
            ISO3166Alpha2CountryCode::DO => ContinentCode::NA,
            ISO3166Alpha2CountryCode::DZ => ContinentCode::AF,
            ISO3166Alpha2CountryCode::EC => ContinentCode::SA,
            ISO3166Alpha2CountryCode::EE => ContinentCode::EU,
            ISO3166Alpha2CountryCode::EG => ContinentCode::AF,
            ISO3166Alpha2CountryCode::EH => ContinentCode::AF,
            ISO3166Alpha2CountryCode::ER => ContinentCode::AF,
            ISO3166Alpha2CountryCode::ES => ContinentCode::EU,
            ISO3166Alpha2CountryCode::ET => ContinentCode::AF,
            ISO3166Alpha2CountryCode::FI => ContinentCode::EU,
            ISO3166Alpha2CountryCode::FJ => ContinentCode::OC,
            ISO3166Alpha2CountryCode::FK => ContinentCode::SA,
            ISO3166Alpha2CountryCode::FM => ContinentCode::OC,
            ISO3166Alpha2CountryCode::FO => ContinentCode::EU,
            ISO3166Alpha2CountryCode::FR => ContinentCode::EU,
            ISO3166Alpha2CountryCode::GA => ContinentCode::AF,
            ISO3166Alpha2CountryCode::GB => ContinentCode::EU,
            ISO3166Alpha2CountryCode::GD => ContinentCode::NA,
            ISO3166Alpha2CountryCode::GE => ContinentCode::AS,
            ISO3166Alpha2CountryCode::GF => ContinentCode::SA,
            ISO3166Alpha2CountryCode::GG => ContinentCode::EU,
            ISO3166Alpha2CountryCode::GH => ContinentCode::AF,
            ISO3166Alpha2CountryCode::GI => ContinentCode::EU,
            ISO3166Alpha2CountryCode::GL => ContinentCode::NA,
            ISO3166Alpha2CountryCode::GM => ContinentCode::AF,
            ISO3166Alpha2CountryCode::GN => ContinentCode::AF,
            ISO3166Alpha2CountryCode::GP => ContinentCode::NA,
            ISO3166Alpha2CountryCode::GQ => ContinentCode::AF,
            ISO3166Alpha2CountryCode::GR => ContinentCode::EU,
            ISO3166Alpha2CountryCode::GS => ContinentCode::AN,
            ISO3166Alpha2CountryCode::GT => ContinentCode::NA,
            ISO3166Alpha2CountryCode::GU => ContinentCode::OC,
            ISO3166Alpha2CountryCode::GW => ContinentCode::AF,
            ISO3166Alpha2CountryCode::GY => ContinentCode::SA,
            ISO3166Alpha2CountryCode::HK => ContinentCode::AS,
            ISO3166Alpha2CountryCode::HM => ContinentCode::AN,
            ISO3166Alpha2CountryCode::HN => ContinentCode::NA,
            ISO3166Alpha2CountryCode::HR => ContinentCode::EU,
            ISO3166Alpha2CountryCode::HT => ContinentCode::NA,
            ISO3166Alpha2CountryCode::HU => ContinentCode::EU,
            ISO3166Alpha2CountryCode::ID => ContinentCode::AS,
            ISO3166Alpha2CountryCode::IE => ContinentCode::EU,
            ISO3166Alpha2CountryCode::IL => ContinentCode::AS,
            ISO3166Alpha2CountryCode::IM => ContinentCode::EU,
            ISO3166Alpha2CountryCode::IN => ContinentCode::AS,
            ISO3166Alpha2CountryCode::IO => ContinentCode::AS,
            ISO3166Alpha2CountryCode::IQ => ContinentCode::AS,
            ISO3166Alpha2CountryCode::IR => ContinentCode::AS,
            ISO3166Alpha2CountryCode::IS => ContinentCode::EU,
            ISO3166Alpha2CountryCode::IT => ContinentCode::EU,
            ISO3166Alpha2CountryCode::JE => ContinentCode::EU,
            ISO3166Alpha2CountryCode::JM => ContinentCode::NA,
            ISO3166Alpha2CountryCode::JO => ContinentCode::AS,
            ISO3166Alpha2CountryCode::JP => ContinentCode::AS,
            ISO3166Alpha2CountryCode::KE => ContinentCode::AF,
            ISO3166Alpha2CountryCode::KG => ContinentCode::AS,
            ISO3166Alpha2CountryCode::KH => ContinentCode::AS,
            ISO3166Alpha2CountryCode::KI => ContinentCode::OC,
            ISO3166Alpha2CountryCode::KM => ContinentCode::AF,
            ISO3166Alpha2CountryCode::KN => ContinentCode::NA,
            ISO3166Alpha2CountryCode::KP => ContinentCode::AS,
            ISO3166Alpha2CountryCode::KR => ContinentCode::AS,
            ISO3166Alpha2CountryCode::XK => ContinentCode::EU,
            ISO3166Alpha2CountryCode::KW => ContinentCode::AS,
            ISO3166Alpha2CountryCode::KY => ContinentCode::NA,
            ISO3166Alpha2CountryCode::KZ => ContinentCode::AS,
            ISO3166Alpha2CountryCode::LA => ContinentCode::AS,
            ISO3166Alpha2CountryCode::LB => ContinentCode::AS,
            ISO3166Alpha2CountryCode::LC => ContinentCode::NA,
            ISO3166Alpha2CountryCode::LI => ContinentCode::EU,
            ISO3166Alpha2CountryCode::LK => ContinentCode::AS,
            ISO3166Alpha2CountryCode::LR => ContinentCode::AF,
            ISO3166Alpha2CountryCode::LS => ContinentCode::AF,
            ISO3166Alpha2CountryCode::LT => ContinentCode::EU,
            ISO3166Alpha2CountryCode::LU => ContinentCode::EU,
            ISO3166Alpha2CountryCode::LV => ContinentCode::EU,
            ISO3166Alpha2CountryCode::LY => ContinentCode::AF,
            ISO3166Alpha2CountryCode::MA => ContinentCode::AF,
            ISO3166Alpha2CountryCode::MC => ContinentCode::EU,
            ISO3166Alpha2CountryCode::MD => ContinentCode::EU,
            ISO3166Alpha2CountryCode::ME => ContinentCode::EU,
            ISO3166Alpha2CountryCode::MF => ContinentCode::NA,
            ISO3166Alpha2CountryCode::MG => ContinentCode::AF,
            ISO3166Alpha2CountryCode::MH => ContinentCode::OC,
            ISO3166Alpha2CountryCode::MK => ContinentCode::EU,
            ISO3166Alpha2CountryCode::ML => ContinentCode::AF,
            ISO3166Alpha2CountryCode::MM => ContinentCode::AS,
            ISO3166Alpha2CountryCode::MN => ContinentCode::AS,
            ISO3166Alpha2CountryCode::MO => ContinentCode::AS,
            ISO3166Alpha2CountryCode::MP => ContinentCode::OC,
            ISO3166Alpha2CountryCode::MQ => ContinentCode::NA,
            ISO3166Alpha2CountryCode::MR => ContinentCode::AF,
            ISO3166Alpha2CountryCode::MS => ContinentCode::NA,
            ISO3166Alpha2CountryCode::MT => ContinentCode::EU,
            ISO3166Alpha2CountryCode::MU => ContinentCode::AF,
            ISO3166Alpha2CountryCode::MV => ContinentCode::AS,
            ISO3166Alpha2CountryCode::MW => ContinentCode::AF,
            ISO3166Alpha2CountryCode::MX => ContinentCode::NA,
            ISO3166Alpha2CountryCode::MY => ContinentCode::AS,
            ISO3166Alpha2CountryCode::MZ => ContinentCode::AF,
            ISO3166Alpha2CountryCode::NA => ContinentCode::AF,
            ISO3166Alpha2CountryCode::NC => ContinentCode::OC,
            ISO3166Alpha2CountryCode::NE => ContinentCode::AF,
            ISO3166Alpha2CountryCode::NF => ContinentCode::OC,
            ISO3166Alpha2CountryCode::NG => ContinentCode::AF,
            ISO3166Alpha2CountryCode::NI => ContinentCode::NA,
            ISO3166Alpha2CountryCode::NL => ContinentCode::EU,
            ISO3166Alpha2CountryCode::NO => ContinentCode::EU,
            ISO3166Alpha2CountryCode::NP => ContinentCode::AS,
            ISO3166Alpha2CountryCode::NR => ContinentCode::OC,
            ISO3166Alpha2CountryCode::NU => ContinentCode::OC,
            ISO3166Alpha2CountryCode::NZ => ContinentCode::OC,
            ISO3166Alpha2CountryCode::OM => ContinentCode::AS,
            ISO3166Alpha2CountryCode::PA => ContinentCode::NA,
            ISO3166Alpha2CountryCode::PE => ContinentCode::SA,
            ISO3166Alpha2CountryCode::PF => ContinentCode::OC,
            ISO3166Alpha2CountryCode::PG => ContinentCode::OC,
            ISO3166Alpha2CountryCode::PH => ContinentCode::AS,
            ISO3166Alpha2CountryCode::PK => ContinentCode::AS,
            ISO3166Alpha2CountryCode::PL => ContinentCode::EU,
            ISO3166Alpha2CountryCode::PM => ContinentCode::NA,
            ISO3166Alpha2CountryCode::PN => ContinentCode::OC,
            ISO3166Alpha2CountryCode::PR => ContinentCode::NA,
            ISO3166Alpha2CountryCode::PS => ContinentCode::AS,
            ISO3166Alpha2CountryCode::PT => ContinentCode::EU,
            ISO3166Alpha2CountryCode::PW => ContinentCode::OC,
            ISO3166Alpha2CountryCode::PY => ContinentCode::SA,
            ISO3166Alpha2CountryCode::QA => ContinentCode::AS,
            ISO3166Alpha2CountryCode::RE => ContinentCode::AF,
            ISO3166Alpha2CountryCode::RO => ContinentCode::EU,
            ISO3166Alpha2CountryCode::RS => ContinentCode::EU,
            ISO3166Alpha2CountryCode::RU => ContinentCode::EU,
            ISO3166Alpha2CountryCode::RW => ContinentCode::AF,
            ISO3166Alpha2CountryCode::SA => ContinentCode::AS,
            ISO3166Alpha2CountryCode::SB => ContinentCode::OC,
            ISO3166Alpha2CountryCode::SC => ContinentCode::AF,
            ISO3166Alpha2CountryCode::SD => ContinentCode::AF,
            ISO3166Alpha2CountryCode::SS => ContinentCode::AF,
            ISO3166Alpha2CountryCode::SE => ContinentCode::EU,
            ISO3166Alpha2CountryCode::SG => ContinentCode::AS,
            ISO3166Alpha2CountryCode::SH => ContinentCode::AF,
            ISO3166Alpha2CountryCode::SI => ContinentCode::EU,
            ISO3166Alpha2CountryCode::SJ => ContinentCode::EU,
            ISO3166Alpha2CountryCode::SK => ContinentCode::EU,
            ISO3166Alpha2CountryCode::SL => ContinentCode::AF,
            ISO3166Alpha2CountryCode::SM => ContinentCode::EU,
            ISO3166Alpha2CountryCode::SN => ContinentCode::AF,
            ISO3166Alpha2CountryCode::SO => ContinentCode::AF,
            ISO3166Alpha2CountryCode::SR => ContinentCode::SA,
            ISO3166Alpha2CountryCode::ST => ContinentCode::AF,
            ISO3166Alpha2CountryCode::SV => ContinentCode::NA,
            ISO3166Alpha2CountryCode::SX => ContinentCode::NA,
            ISO3166Alpha2CountryCode::SY => ContinentCode::AS,
            ISO3166Alpha2CountryCode::SZ => ContinentCode::AF,
            ISO3166Alpha2CountryCode::TC => ContinentCode::NA,
            ISO3166Alpha2CountryCode::TD => ContinentCode::AF,
            ISO3166Alpha2CountryCode::TF => ContinentCode::AN,
            ISO3166Alpha2CountryCode::TG => ContinentCode::AF,
            ISO3166Alpha2CountryCode::TH => ContinentCode::AS,
            ISO3166Alpha2CountryCode::TJ => ContinentCode::AS,
            ISO3166Alpha2CountryCode::TK => ContinentCode::OC,
            ISO3166Alpha2CountryCode::TL => ContinentCode::OC,
            ISO3166Alpha2CountryCode::TM => ContinentCode::AS,
            ISO3166Alpha2CountryCode::TN => ContinentCode::AF,
            ISO3166Alpha2CountryCode::TO => ContinentCode::OC,
            ISO3166Alpha2CountryCode::TR => ContinentCode::AS,
            ISO3166Alpha2CountryCode::TT => ContinentCode::NA,
            ISO3166Alpha2CountryCode::TV => ContinentCode::OC,
            ISO3166Alpha2CountryCode::TW => ContinentCode::AS,
            ISO3166Alpha2CountryCode::TZ => ContinentCode::AF,
            ISO3166Alpha2CountryCode::UA => ContinentCode::EU,
            ISO3166Alpha2CountryCode::UG => ContinentCode::AF,
            ISO3166Alpha2CountryCode::UM => ContinentCode::OC,
            ISO3166Alpha2CountryCode::US => ContinentCode::NA,
            ISO3166Alpha2CountryCode::UY => ContinentCode::SA,
            ISO3166Alpha2CountryCode::UZ => ContinentCode::AS,
            ISO3166Alpha2CountryCode::VA => ContinentCode::EU,
            ISO3166Alpha2CountryCode::VC => ContinentCode::NA,
            ISO3166Alpha2CountryCode::VE => ContinentCode::SA,
            ISO3166Alpha2CountryCode::VG => ContinentCode::NA,
            ISO3166Alpha2CountryCode::VI => ContinentCode::NA,
            ISO3166Alpha2CountryCode::VN => ContinentCode::AS,
            ISO3166Alpha2CountryCode::VU => ContinentCode::OC,
            ISO3166Alpha2CountryCode::WF => ContinentCode::OC,
            ISO3166Alpha2CountryCode::WS => ContinentCode::OC,
            ISO3166Alpha2CountryCode::YE => ContinentCode::AS,
            ISO3166Alpha2CountryCode::YT => ContinentCode::AF,
            ISO3166Alpha2CountryCode::ZA => ContinentCode::AF,
            ISO3166Alpha2CountryCode::ZM => ContinentCode::AF,
            ISO3166Alpha2CountryCode::ZW => ContinentCode::AF,
            ISO3166Alpha2CountryCode::CS => ContinentCode::EU,
            ISO3166Alpha2CountryCode::AN => ContinentCode::NA,
        }
    }
}

impl FromStr for ISO3166Alpha2CountryCode {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AD" | "ad" => Ok(ISO3166Alpha2CountryCode::AD),
            "AE" | "ae" => Ok(ISO3166Alpha2CountryCode::AE),
            "AF" | "af" => Ok(ISO3166Alpha2CountryCode::AF),
            "AG" | "ag" => Ok(ISO3166Alpha2CountryCode::AG),
            "AI" | "ai" => Ok(ISO3166Alpha2CountryCode::AI),
            "AL" | "al" => Ok(ISO3166Alpha2CountryCode::AL),
            "AM" | "am" => Ok(ISO3166Alpha2CountryCode::AM),
            "AO" | "ao" => Ok(ISO3166Alpha2CountryCode::AO),
            "AQ" | "aq" => Ok(ISO3166Alpha2CountryCode::AQ),
            "AR" | "ar" => Ok(ISO3166Alpha2CountryCode::AR),
            "AS" | "as" => Ok(ISO3166Alpha2CountryCode::AS),
            "AT" | "at" => Ok(ISO3166Alpha2CountryCode::AT),
            "AU" | "au" => Ok(ISO3166Alpha2CountryCode::AU),
            "AW" | "aw" => Ok(ISO3166Alpha2CountryCode::AW),
            "AX" | "ax" => Ok(ISO3166Alpha2CountryCode::AX),
            "AZ" | "az" => Ok(ISO3166Alpha2CountryCode::AZ),
            "BA" | "ba" => Ok(ISO3166Alpha2CountryCode::BA),
            "BB" | "bb" => Ok(ISO3166Alpha2CountryCode::BB),
            "BD" | "bd" => Ok(ISO3166Alpha2CountryCode::BD),
            "BE" | "be" => Ok(ISO3166Alpha2CountryCode::BE),
            "BF" | "bf" => Ok(ISO3166Alpha2CountryCode::BF),
            "BG" | "bg" => Ok(ISO3166Alpha2CountryCode::BG),
            "BH" | "bh" => Ok(ISO3166Alpha2CountryCode::BH),
            "BI" | "bi" => Ok(ISO3166Alpha2CountryCode::BI),
            "BJ" | "bj" => Ok(ISO3166Alpha2CountryCode::BJ),
            "BL" | "bl" => Ok(ISO3166Alpha2CountryCode::BL),
            "BM" | "bm" => Ok(ISO3166Alpha2CountryCode::BM),
            "BN" | "bn" => Ok(ISO3166Alpha2CountryCode::BN),
            "BO" | "bo" => Ok(ISO3166Alpha2CountryCode::BO),
            "BQ" | "bq" => Ok(ISO3166Alpha2CountryCode::BQ),
            "BR" | "br" => Ok(ISO3166Alpha2CountryCode::BR),
            "BS" | "bs" => Ok(ISO3166Alpha2CountryCode::BS),
            "BT" | "bt" => Ok(ISO3166Alpha2CountryCode::BT),
            "BV" | "bv" => Ok(ISO3166Alpha2CountryCode::BV),
            "BW" | "bw" => Ok(ISO3166Alpha2CountryCode::BW),
            "BY" | "by" => Ok(ISO3166Alpha2CountryCode::BY),
            "BZ" | "bz" => Ok(ISO3166Alpha2CountryCode::BZ),
            "CA" | "ca" => Ok(ISO3166Alpha2CountryCode::CA),
            "CC" | "cc" => Ok(ISO3166Alpha2CountryCode::CC),
            "CD" | "cd" => Ok(ISO3166Alpha2CountryCode::CD),
            "CF" | "cf" => Ok(ISO3166Alpha2CountryCode::CF),
            "CG" | "cg" => Ok(ISO3166Alpha2CountryCode::CG),
            "CH" | "ch" => Ok(ISO3166Alpha2CountryCode::CH),
            "CI" | "ci" => Ok(ISO3166Alpha2CountryCode::CI),
            "CK" | "ck" => Ok(ISO3166Alpha2CountryCode::CK),
            "CL" | "cl" => Ok(ISO3166Alpha2CountryCode::CL),
            "CM" | "cm" => Ok(ISO3166Alpha2CountryCode::CM),
            "CN" | "cn" => Ok(ISO3166Alpha2CountryCode::CN),
            "CO" | "co" => Ok(ISO3166Alpha2CountryCode::CO),
            "CR" | "cr" => Ok(ISO3166Alpha2CountryCode::CR),
            "CU" | "cu" => Ok(ISO3166Alpha2CountryCode::CU),
            "CV" | "cv" => Ok(ISO3166Alpha2CountryCode::CV),
            "CW" | "cw" => Ok(ISO3166Alpha2CountryCode::CW),
            "CX" | "cx" => Ok(ISO3166Alpha2CountryCode::CX),
            "CY" | "cy" => Ok(ISO3166Alpha2CountryCode::CY),
            "CZ" | "cz" => Ok(ISO3166Alpha2CountryCode::CZ),
            "DE" | "de" => Ok(ISO3166Alpha2CountryCode::DE),
            "DJ" | "dj" => Ok(ISO3166Alpha2CountryCode::DJ),
            "DK" | "dk" => Ok(ISO3166Alpha2CountryCode::DK),
            "DM" | "dm" => Ok(ISO3166Alpha2CountryCode::DM),
            "DO" | "do" => Ok(ISO3166Alpha2CountryCode::DO),
            "DZ" | "dz" => Ok(ISO3166Alpha2CountryCode::DZ),
            "EC" | "ec" => Ok(ISO3166Alpha2CountryCode::EC),
            "EE" | "ee" => Ok(ISO3166Alpha2CountryCode::EE),
            "EG" | "eg" => Ok(ISO3166Alpha2CountryCode::EG),
            "EH" | "eh" => Ok(ISO3166Alpha2CountryCode::EH),
            "ER" | "er" => Ok(ISO3166Alpha2CountryCode::ER),
            "ES" | "es" => Ok(ISO3166Alpha2CountryCode::ES),
            "ET" | "et" => Ok(ISO3166Alpha2CountryCode::ET),
            "FI" | "fi" => Ok(ISO3166Alpha2CountryCode::FI),
            "FJ" | "fj" => Ok(ISO3166Alpha2CountryCode::FJ),
            "FK" | "fk" => Ok(ISO3166Alpha2CountryCode::FK),
            "FM" | "fm" => Ok(ISO3166Alpha2CountryCode::FM),
            "FO" | "fo" => Ok(ISO3166Alpha2CountryCode::FO),
            "FR" | "fr" => Ok(ISO3166Alpha2CountryCode::FR),
            "GA" | "ga" => Ok(ISO3166Alpha2CountryCode::GA),
            "GB" | "gb" => Ok(ISO3166Alpha2CountryCode::GB),
            "GD" | "gd" => Ok(ISO3166Alpha2CountryCode::GD),
            "GE" | "ge" => Ok(ISO3166Alpha2CountryCode::GE),
            "GF" | "gf" => Ok(ISO3166Alpha2CountryCode::GF),
            "GG" | "gg" => Ok(ISO3166Alpha2CountryCode::GG),
            "GH" | "gh" => Ok(ISO3166Alpha2CountryCode::GH),
            "GI" | "gi" => Ok(ISO3166Alpha2CountryCode::GI),
            "GL" | "gl" => Ok(ISO3166Alpha2CountryCode::GL),
            "GM" | "gm" => Ok(ISO3166Alpha2CountryCode::GM),
            "GN" | "gn" => Ok(ISO3166Alpha2CountryCode::GN),
            "GP" | "gp" => Ok(ISO3166Alpha2CountryCode::GP),
            "GQ" | "gq" => Ok(ISO3166Alpha2CountryCode::GQ),
            "GR" | "gr" => Ok(ISO3166Alpha2CountryCode::GR),
            "GS" | "gs" => Ok(ISO3166Alpha2CountryCode::GS),
            "GT" | "gt" => Ok(ISO3166Alpha2CountryCode::GT),
            "GU" | "gu" => Ok(ISO3166Alpha2CountryCode::GU),
            "GW" | "gw" => Ok(ISO3166Alpha2CountryCode::GW),
            "GY" | "gy" => Ok(ISO3166Alpha2CountryCode::GY),
            "HK" | "hk" => Ok(ISO3166Alpha2CountryCode::HK),
            "HM" | "hm" => Ok(ISO3166Alpha2CountryCode::HM),
            "HN" | "hn" => Ok(ISO3166Alpha2CountryCode::HN),
            "HR" | "hr" => Ok(ISO3166Alpha2CountryCode::HR),
            "HT" | "ht" => Ok(ISO3166Alpha2CountryCode::HT),
            "HU" | "hu" => Ok(ISO3166Alpha2CountryCode::HU),
            "ID" | "id" => Ok(ISO3166Alpha2CountryCode::ID),
            "IE" | "ie" => Ok(ISO3166Alpha2CountryCode::IE),
            "IL" | "il" => Ok(ISO3166Alpha2CountryCode::IL),
            "IM" | "im" => Ok(ISO3166Alpha2CountryCode::IM),
            "IN" | "in" => Ok(ISO3166Alpha2CountryCode::IN),
            "IO" | "io" => Ok(ISO3166Alpha2CountryCode::IO),
            "IQ" | "iq" => Ok(ISO3166Alpha2CountryCode::IQ),
            "IR" | "ir" => Ok(ISO3166Alpha2CountryCode::IR),
            "IS" | "is" => Ok(ISO3166Alpha2CountryCode::IS),
            "IT" | "it" => Ok(ISO3166Alpha2CountryCode::IT),
            "JE" | "je" => Ok(ISO3166Alpha2CountryCode::JE),
            "JM" | "jm" => Ok(ISO3166Alpha2CountryCode::JM),
            "JO" | "jo" => Ok(ISO3166Alpha2CountryCode::JO),
            "JP" | "jp" => Ok(ISO3166Alpha2CountryCode::JP),
            "KE" | "ke" => Ok(ISO3166Alpha2CountryCode::KE),
            "KG" | "kg" => Ok(ISO3166Alpha2CountryCode::KG),
            "KH" | "kh" => Ok(ISO3166Alpha2CountryCode::KH),
            "KI" | "ki" => Ok(ISO3166Alpha2CountryCode::KI),
            "KM" | "km" => Ok(ISO3166Alpha2CountryCode::KM),
            "KN" | "kn" => Ok(ISO3166Alpha2CountryCode::KN),
            "KP" | "kp" => Ok(ISO3166Alpha2CountryCode::KP),
            "KR" | "kr" => Ok(ISO3166Alpha2CountryCode::KR),
            "XK" | "xk" => Ok(ISO3166Alpha2CountryCode::XK),
            "KW" | "kw" => Ok(ISO3166Alpha2CountryCode::KW),
            "KY" | "ky" => Ok(ISO3166Alpha2CountryCode::KY),
            "KZ" | "kz" => Ok(ISO3166Alpha2CountryCode::KZ),
            "LA" | "la" => Ok(ISO3166Alpha2CountryCode::LA),
            "LB" | "lb" => Ok(ISO3166Alpha2CountryCode::LB),
            "LC" | "lc" => Ok(ISO3166Alpha2CountryCode::LC),
            "LI" | "li" => Ok(ISO3166Alpha2CountryCode::LI),
            "LK" | "lk" => Ok(ISO3166Alpha2CountryCode::LK),
            "LR" | "lr" => Ok(ISO3166Alpha2CountryCode::LR),
            "LS" | "ls" => Ok(ISO3166Alpha2CountryCode::LS),
            "LT" | "lt" => Ok(ISO3166Alpha2CountryCode::LT),
            "LU" | "lu" => Ok(ISO3166Alpha2CountryCode::LU),
            "LV" | "lv" => Ok(ISO3166Alpha2CountryCode::LV),
            "LY" | "ly" => Ok(ISO3166Alpha2CountryCode::LY),
            "MA" | "ma" => Ok(ISO3166Alpha2CountryCode::MA),
            "MC" | "mc" => Ok(ISO3166Alpha2CountryCode::MC),
            "MD" | "md" => Ok(ISO3166Alpha2CountryCode::MD),
            "ME" | "me" => Ok(ISO3166Alpha2CountryCode::ME),
            "MF" | "mf" => Ok(ISO3166Alpha2CountryCode::MF),
            "MG" | "mg" => Ok(ISO3166Alpha2CountryCode::MG),
            "MH" | "mh" => Ok(ISO3166Alpha2CountryCode::MH),
            "MK" | "mk" => Ok(ISO3166Alpha2CountryCode::MK),
            "ML" | "ml" => Ok(ISO3166Alpha2CountryCode::ML),
            "MM" | "mm" => Ok(ISO3166Alpha2CountryCode::MM),
            "MN" | "mn" => Ok(ISO3166Alpha2CountryCode::MN),
            "MO" | "mo" => Ok(ISO3166Alpha2CountryCode::MO),
            "MP" | "mp" => Ok(ISO3166Alpha2CountryCode::MP),
            "MQ" | "mq" => Ok(ISO3166Alpha2CountryCode::MQ),
            "MR" | "mr" => Ok(ISO3166Alpha2CountryCode::MR),
            "MS" | "ms" => Ok(ISO3166Alpha2CountryCode::MS),
            "MT" | "mt" => Ok(ISO3166Alpha2CountryCode::MT),
            "MU" | "mu" => Ok(ISO3166Alpha2CountryCode::MU),
            "MV" | "mv" => Ok(ISO3166Alpha2CountryCode::MV),
            "MW" | "mw" => Ok(ISO3166Alpha2CountryCode::MW),
            "MX" | "mx" => Ok(ISO3166Alpha2CountryCode::MX),
            "MY" | "my" => Ok(ISO3166Alpha2CountryCode::MY),
            "MZ" | "mz" => Ok(ISO3166Alpha2CountryCode::MZ),
            "NA" | "na" => Ok(ISO3166Alpha2CountryCode::NA),
            "NC" | "nc" => Ok(ISO3166Alpha2CountryCode::NC),
            "NE" | "ne" => Ok(ISO3166Alpha2CountryCode::NE),
            "NF" | "nf" => Ok(ISO3166Alpha2CountryCode::NF),
            "NG" | "ng" => Ok(ISO3166Alpha2CountryCode::NG),
            "NI" | "ni" => Ok(ISO3166Alpha2CountryCode::NI),
            "NL" | "nl" => Ok(ISO3166Alpha2CountryCode::NL),
            "NO" | "no" => Ok(ISO3166Alpha2CountryCode::NO),
            "NP" | "np" => Ok(ISO3166Alpha2CountryCode::NP),
            "NR" | "nr" => Ok(ISO3166Alpha2CountryCode::NR),
            "NU" | "nu" => Ok(ISO3166Alpha2CountryCode::NU),
            "NZ" | "nz" => Ok(ISO3166Alpha2CountryCode::NZ),
            "OM" | "om" => Ok(ISO3166Alpha2CountryCode::OM),
            "PA" | "pa" => Ok(ISO3166Alpha2CountryCode::PA),
            "PE" | "pe" => Ok(ISO3166Alpha2CountryCode::PE),
            "PF" | "pf" => Ok(ISO3166Alpha2CountryCode::PF),
            "PG" | "pg" => Ok(ISO3166Alpha2CountryCode::PG),
            "PH" | "ph" => Ok(ISO3166Alpha2CountryCode::PH),
            "PK" | "pk" => Ok(ISO3166Alpha2CountryCode::PK),
            "PL" | "pl" => Ok(ISO3166Alpha2CountryCode::PL),
            "PM" | "pm" => Ok(ISO3166Alpha2CountryCode::PM),
            "PN" | "pn" => Ok(ISO3166Alpha2CountryCode::PN),
            "PR" | "pr" => Ok(ISO3166Alpha2CountryCode::PR),
            "PS" | "ps" => Ok(ISO3166Alpha2CountryCode::PS),
            "PT" | "pt" => Ok(ISO3166Alpha2CountryCode::PT),
            "PW" | "pw" => Ok(ISO3166Alpha2CountryCode::PW),
            "PY" | "py" => Ok(ISO3166Alpha2CountryCode::PY),
            "QA" | "qa" => Ok(ISO3166Alpha2CountryCode::QA),
            "RE" | "re" => Ok(ISO3166Alpha2CountryCode::RE),
            "RO" | "ro" => Ok(ISO3166Alpha2CountryCode::RO),
            "RS" | "rs" => Ok(ISO3166Alpha2CountryCode::RS),
            "RU" | "ru" => Ok(ISO3166Alpha2CountryCode::RU),
            "RW" | "rw" => Ok(ISO3166Alpha2CountryCode::RW),
            "SA" | "sa" => Ok(ISO3166Alpha2CountryCode::SA),
            "SB" | "sb" => Ok(ISO3166Alpha2CountryCode::SB),
            "SC" | "sc" => Ok(ISO3166Alpha2CountryCode::SC),
            "SD" | "sd" => Ok(ISO3166Alpha2CountryCode::SD),
            "SS" | "ss" => Ok(ISO3166Alpha2CountryCode::SS),
            "SE" | "se" => Ok(ISO3166Alpha2CountryCode::SE),
            "SG" | "sg" => Ok(ISO3166Alpha2CountryCode::SG),
            "SH" | "sh" => Ok(ISO3166Alpha2CountryCode::SH),
            "SI" | "si" => Ok(ISO3166Alpha2CountryCode::SI),
            "SJ" | "sj" => Ok(ISO3166Alpha2CountryCode::SJ),
            "SK" | "sk" => Ok(ISO3166Alpha2CountryCode::SK),
            "SL" | "sl" => Ok(ISO3166Alpha2CountryCode::SL),
            "SM" | "sm" => Ok(ISO3166Alpha2CountryCode::SM),
            "SN" | "sn" => Ok(ISO3166Alpha2CountryCode::SN),
            "SO" | "so" => Ok(ISO3166Alpha2CountryCode::SO),
            "SR" | "sr" => Ok(ISO3166Alpha2CountryCode::SR),
            "ST" | "st" => Ok(ISO3166Alpha2CountryCode::ST),
            "SV" | "sv" => Ok(ISO3166Alpha2CountryCode::SV),
            "SX" | "sx" => Ok(ISO3166Alpha2CountryCode::SX),
            "SY" | "sy" => Ok(ISO3166Alpha2CountryCode::SY),
            "SZ" | "sz" => Ok(ISO3166Alpha2CountryCode::SZ),
            "TC" | "tc" => Ok(ISO3166Alpha2CountryCode::TC),
            "TD" | "td" => Ok(ISO3166Alpha2CountryCode::TD),
            "TF" | "tf" => Ok(ISO3166Alpha2CountryCode::TF),
            "TG" | "tg" => Ok(ISO3166Alpha2CountryCode::TG),
            "TH" | "th" => Ok(ISO3166Alpha2CountryCode::TH),
            "TJ" | "tj" => Ok(ISO3166Alpha2CountryCode::TJ),
            "TK" | "tk" => Ok(ISO3166Alpha2CountryCode::TK),
            "TL" | "tl" => Ok(ISO3166Alpha2CountryCode::TL),
            "TM" | "tm" => Ok(ISO3166Alpha2CountryCode::TM),
            "TN" | "tn" => Ok(ISO3166Alpha2CountryCode::TN),
            "TO" | "to" => Ok(ISO3166Alpha2CountryCode::TO),
            "TR" | "tr" => Ok(ISO3166Alpha2CountryCode::TR),
            "TT" | "tt" => Ok(ISO3166Alpha2CountryCode::TT),
            "TV" | "tv" => Ok(ISO3166Alpha2CountryCode::TV),
            "TW" | "tw" => Ok(ISO3166Alpha2CountryCode::TW),
            "TZ" | "tz" => Ok(ISO3166Alpha2CountryCode::TZ),
            "UA" | "ua" => Ok(ISO3166Alpha2CountryCode::UA),
            "UG" | "ug" => Ok(ISO3166Alpha2CountryCode::UG),
            "UM" | "um" => Ok(ISO3166Alpha2CountryCode::UM),
            "US" | "us" => Ok(ISO3166Alpha2CountryCode::US),
            "UY" | "uy" => Ok(ISO3166Alpha2CountryCode::UY),
            "UZ" | "uz" => Ok(ISO3166Alpha2CountryCode::UZ),
            "VA" | "va" => Ok(ISO3166Alpha2CountryCode::VA),
            "VC" | "vc" => Ok(ISO3166Alpha2CountryCode::VC),
            "VE" | "ve" => Ok(ISO3166Alpha2CountryCode::VE),
            "VG" | "vg" => Ok(ISO3166Alpha2CountryCode::VG),
            "VI" | "vi" => Ok(ISO3166Alpha2CountryCode::VI),
            "VN" | "vn" => Ok(ISO3166Alpha2CountryCode::VN),
            "VU" | "vu" => Ok(ISO3166Alpha2CountryCode::VU),
            "WF" | "wf" => Ok(ISO3166Alpha2CountryCode::WF),
            "WS" | "ws" => Ok(ISO3166Alpha2CountryCode::WS),
            "YE" | "ye" => Ok(ISO3166Alpha2CountryCode::YE),
            "YT" | "yt" => Ok(ISO3166Alpha2CountryCode::YT),
            "ZA" | "za" => Ok(ISO3166Alpha2CountryCode::ZA),
            "ZM" | "zm" => Ok(ISO3166Alpha2CountryCode::ZM),
            "ZW" | "zw" => Ok(ISO3166Alpha2CountryCode::ZW),
            "CS" | "cs" => Ok(ISO3166Alpha2CountryCode::CS),
            "AN" | "an" => Ok(ISO3166Alpha2CountryCode::AN),
            _ => Err(()),
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub enum ISO3166Alpha3CountryCode {
    AND, /* Andorra */
    ARE, /* United Arab Emirates */
    AFG, /* Afghanistan */
    ATG, /* Antigua and Barbuda */
    AIA, /* Anguilla */
    ALB, /* Albania */
    ARM, /* Armenia */
    AGO, /* Angola */
    ATA, /* Antarctica */
    ARG, /* Argentina */
    ASM, /* American Samoa */
    AUT, /* Austria */
    AUS, /* Australia */
    ABW, /* Aruba */
    ALA, /* Aland Islands */
    AZE, /* Azerbaijan */
    BIH, /* Bosnia and Herzegovina */
    BRB, /* Barbados */
    BGD, /* Bangladesh */
    BEL, /* Belgium */
    BFA, /* Burkina Faso */
    BGR, /* Bulgaria */
    BHR, /* Bahrain */
    BDI, /* Burundi */
    BEN, /* Benin */
    BLM, /* Saint Barthelemy */
    BMU, /* Bermuda */
    BRN, /* Brunei */
    BOL, /* Bolivia */
    BES, /* Bonaire, Saint Eustatius and Saba  */
    BRA, /* Brazil */
    BHS, /* Bahamas */
    BTN, /* Bhutan */
    BVT, /* Bouvet Island */
    BWA, /* Botswana */
    BLR, /* Belarus */
    BLZ, /* Belize */
    CAN, /* Canada */
    CCK, /* Cocos Islands */
    COD, /* Democratic Republic of the Congo */
    CAF, /* Central African Republic */
    COG, /* Republic of the Congo */
    CHE, /* Switzerland */
    CIV, /* Ivory Coast */
    COK, /* Cook Islands */
    CHL, /* Chile */
    CMR, /* Cameroon */
    CHN, /* China */
    COL, /* Colombia */
    CRI, /* Costa Rica */
    CUB, /* Cuba */
    CPV, /* Cabo Verde */
    CUW, /* Curacao */
    CXR, /* Christmas Island */
    CYP, /* Cyprus */
    CZE, /* Czechia */
    DEU, /* Germany */
    DJI, /* Djibouti */
    DNK, /* Denmark */
    DMA, /* Dominica */
    DOM, /* Dominican Republic */
    DZA, /* Algeria */
    ECU, /* Ecuador */
    EST, /* Estonia */
    EGY, /* Egypt */
    ESH, /* Western Sahara */
    ERI, /* Eritrea */
    ESP, /* Spain */
    ETH, /* Ethiopia */
    FIN, /* Finland */
    FJI, /* Fiji */
    FLK, /* Falkland Islands */
    FSM, /* Micronesia */
    FRO, /* Faroe Islands */
    FRA, /* France */
    GAB, /* Gabon */
    GBR, /* United Kingdom */
    GRD, /* Grenada */
    GEO, /* Georgia */
    GUF, /* French Guiana */
    GGY, /* Guernsey */
    GHA, /* Ghana */
    GIB, /* Gibraltar */
    GRL, /* Greenland */
    GMB, /* Gambia */
    GIN, /* Guinea */
    GLP, /* Guadeloupe */
    GNQ, /* Equatorial Guinea */
    GRC, /* Greece */
    SGS, /* South Georgia and the South Sandwich Islands */
    GTM, /* Guatemala */
    GUM, /* Guam */
    GNB, /* Guinea-Bissau */
    GUY, /* Guyana */
    HKG, /* Hong Kong */
    HMD, /* Heard Island and McDonald Islands */
    HND, /* Honduras */
    HRV, /* Croatia */
    HTI, /* Haiti */
    HUN, /* Hungary */
    IDN, /* Indonesia */
    IRL, /* Ireland */
    ISR, /* Israel */
    IMN, /* Isle of Man */
    IND, /* India */
    IOT, /* British Indian Ocean Territory */
    IRQ, /* Iraq */
    IRN, /* Iran */
    ISL, /* Iceland */
    ITA, /* Italy */
    JEY, /* Jersey */
    JAM, /* Jamaica */
    JOR, /* Jordan */
    JPN, /* Japan */
    KEN, /* Kenya */
    KGZ, /* Kyrgyzstan */
    KHM, /* Cambodia */
    KIR, /* Kiribati */
    COM, /* Comoros */
    KNA, /* Saint Kitts and Nevis */
    PRK, /* North Korea */
    KOR, /* South Korea */
    XKX, /* Kosovo */
    KWT, /* Kuwait */
    CYM, /* Cayman Islands */
    KAZ, /* Kazakhstan */
    LAO, /* Laos */
    LBN, /* Lebanon */
    LCA, /* Saint Lucia */
    LIE, /* Liechtenstein */
    LKA, /* Sri Lanka */
    LBR, /* Liberia */
    LSO, /* Lesotho */
    LTU, /* Lithuania */
    LUX, /* Luxembourg */
    LVA, /* Latvia */
    LBY, /* Libya */
    MAR, /* Morocco */
    MCO, /* Monaco */
    MDA, /* Moldova */
    MNE, /* Montenegro */
    MAF, /* Saint Martin */
    MDG, /* Madagascar */
    MHL, /* Marshall Islands */
    MKD, /* North Macedonia */
    MLI, /* Mali */
    MMR, /* Myanmar */
    MNG, /* Mongolia */
    MAC, /* Macao */
    MNP, /* Northern Mariana Islands */
    MTQ, /* Martinique */
    MRT, /* Mauritania */
    MSR, /* Montserrat */
    MLT, /* Malta */
    MUS, /* Mauritius */
    MDV, /* Maldives */
    MWI, /* Malawi */
    MEX, /* Mexico */
    MYS, /* Malaysia */
    MOZ, /* Mozambique */
    NAM, /* Namibia */
    NCL, /* New Caledonia */
    NER, /* Niger */
    NFK, /* Norfolk Island */
    NGA, /* Nigeria */
    NIC, /* Nicaragua */
    NLD, /* Netherlands */
    NOR, /* Norway */
    NPL, /* Nepal */
    NRU, /* Nauru */
    NIU, /* Niue */
    NZL, /* New Zealand */
    OMN, /* Oman */
    PAN, /* Panama */
    PER, /* Peru */
    PYF, /* French Polynesia */
    PNG, /* Papua New Guinea */
    PHL, /* Philippines */
    PAK, /* Pakistan */
    POL, /* Poland */
    SPM, /* Saint Pierre and Miquelon */
    PCN, /* Pitcairn */
    PRI, /* Puerto Rico */
    PSE, /* Palestinian Territory */
    PRT, /* Portugal */
    PLW, /* Palau */
    PRY, /* Paraguay */
    QAT, /* Qatar */
    REU, /* Reunion */
    ROU, /* Romania */
    SRB, /* Serbia */
    RUS, /* Russia */
    RWA, /* Rwanda */
    SAU, /* Saudi Arabia */
    SLB, /* Solomon Islands */
    SYC, /* Seychelles */
    SDN, /* Sudan */
    SSD, /* South Sudan */
    SWE, /* Sweden */
    SGP, /* Singapore */
    SHN, /* Saint Helena */
    SVN, /* Slovenia */
    SJM, /* Svalbard and Jan Mayen */
    SVK, /* Slovakia */
    SLE, /* Sierra Leone */
    SMR, /* San Marino */
    SEN, /* Senegal */
    SOM, /* Somalia */
    SUR, /* Suriname */
    STP, /* Sao Tome and Principe */
    SLV, /* El Salvador */
    SXM, /* Sint Maarten */
    SYR, /* Syria */
    SWZ, /* Eswatini */
    TCA, /* Turks and Caicos Islands */
    TCD, /* Chad */
    ATF, /* French Southern Territories */
    TGO, /* Togo */
    THA, /* Thailand */
    TJK, /* Tajikistan */
    TKL, /* Tokelau */
    TLS, /* Timor Leste */
    TKM, /* Turkmenistan */
    TUN, /* Tunisia */
    TON, /* Tonga */
    TUR, /* Turkey */
    TTO, /* Trinidad and Tobago */
    TUV, /* Tuvalu */
    TWN, /* Taiwan */
    TZA, /* Tanzania */
    UKR, /* Ukraine */
    UGA, /* Uganda */
    UMI, /* United States Minor Outlying Islands */
    USA, /* United States */
    URY, /* Uruguay */
    UZB, /* Uzbekistan */
    VAT, /* Vatican */
    VCT, /* Saint Vincent and the Grenadines */
    VEN, /* Venezuela */
    VGB, /* British Virgin Islands */
    VIR, /* U.S. Virgin Islands */
    VNM, /* Vietnam */
    VUT, /* Vanuatu */
    WLF, /* Wallis and Futuna */
    WSM, /* Samoa */
    YEM, /* Yemen */
    MYT, /* Mayotte */
    ZAF, /* South Africa */
    ZMB, /* Zambia */
    ZWE, /* Zimbabwe */
    SCG, /* Serbia and Montenegro */
    ANT, /* Netherlands Antilles */
}

impl ISO3166Alpha3CountryCode {
    pub fn name(&self) -> &'static str {
        ALL_COUNTRY_NAMES[*self as usize]
    }

    pub fn continent(&self) -> ContinentCode {
        match self {
            ISO3166Alpha3CountryCode::AND => ContinentCode::EU,
            ISO3166Alpha3CountryCode::ARE => ContinentCode::AS,
            ISO3166Alpha3CountryCode::AFG => ContinentCode::AS,
            ISO3166Alpha3CountryCode::ATG => ContinentCode::NA,
            ISO3166Alpha3CountryCode::AIA => ContinentCode::NA,
            ISO3166Alpha3CountryCode::ALB => ContinentCode::EU,
            ISO3166Alpha3CountryCode::ARM => ContinentCode::AS,
            ISO3166Alpha3CountryCode::AGO => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ATA => ContinentCode::AN,
            ISO3166Alpha3CountryCode::ARG => ContinentCode::SA,
            ISO3166Alpha3CountryCode::ASM => ContinentCode::OC,
            ISO3166Alpha3CountryCode::AUT => ContinentCode::EU,
            ISO3166Alpha3CountryCode::AUS => ContinentCode::OC,
            ISO3166Alpha3CountryCode::ABW => ContinentCode::NA,
            ISO3166Alpha3CountryCode::ALA => ContinentCode::EU,
            ISO3166Alpha3CountryCode::AZE => ContinentCode::AS,
            ISO3166Alpha3CountryCode::BIH => ContinentCode::EU,
            ISO3166Alpha3CountryCode::BRB => ContinentCode::NA,
            ISO3166Alpha3CountryCode::BGD => ContinentCode::AS,
            ISO3166Alpha3CountryCode::BEL => ContinentCode::EU,
            ISO3166Alpha3CountryCode::BFA => ContinentCode::AF,
            ISO3166Alpha3CountryCode::BGR => ContinentCode::EU,
            ISO3166Alpha3CountryCode::BHR => ContinentCode::AS,
            ISO3166Alpha3CountryCode::BDI => ContinentCode::AF,
            ISO3166Alpha3CountryCode::BEN => ContinentCode::AF,
            ISO3166Alpha3CountryCode::BLM => ContinentCode::NA,
            ISO3166Alpha3CountryCode::BMU => ContinentCode::NA,
            ISO3166Alpha3CountryCode::BRN => ContinentCode::AS,
            ISO3166Alpha3CountryCode::BOL => ContinentCode::SA,
            ISO3166Alpha3CountryCode::BES => ContinentCode::NA,
            ISO3166Alpha3CountryCode::BRA => ContinentCode::SA,
            ISO3166Alpha3CountryCode::BHS => ContinentCode::NA,
            ISO3166Alpha3CountryCode::BTN => ContinentCode::AS,
            ISO3166Alpha3CountryCode::BVT => ContinentCode::AN,
            ISO3166Alpha3CountryCode::BWA => ContinentCode::AF,
            ISO3166Alpha3CountryCode::BLR => ContinentCode::EU,
            ISO3166Alpha3CountryCode::BLZ => ContinentCode::NA,
            ISO3166Alpha3CountryCode::CAN => ContinentCode::NA,
            ISO3166Alpha3CountryCode::CCK => ContinentCode::AS,
            ISO3166Alpha3CountryCode::COD => ContinentCode::AF,
            ISO3166Alpha3CountryCode::CAF => ContinentCode::AF,
            ISO3166Alpha3CountryCode::COG => ContinentCode::AF,
            ISO3166Alpha3CountryCode::CHE => ContinentCode::EU,
            ISO3166Alpha3CountryCode::CIV => ContinentCode::AF,
            ISO3166Alpha3CountryCode::COK => ContinentCode::OC,
            ISO3166Alpha3CountryCode::CHL => ContinentCode::SA,
            ISO3166Alpha3CountryCode::CMR => ContinentCode::AF,
            ISO3166Alpha3CountryCode::CHN => ContinentCode::AS,
            ISO3166Alpha3CountryCode::COL => ContinentCode::SA,
            ISO3166Alpha3CountryCode::CRI => ContinentCode::NA,
            ISO3166Alpha3CountryCode::CUB => ContinentCode::NA,
            ISO3166Alpha3CountryCode::CPV => ContinentCode::AF,
            ISO3166Alpha3CountryCode::CUW => ContinentCode::NA,
            ISO3166Alpha3CountryCode::CXR => ContinentCode::OC,
            ISO3166Alpha3CountryCode::CYP => ContinentCode::EU,
            ISO3166Alpha3CountryCode::CZE => ContinentCode::EU,
            ISO3166Alpha3CountryCode::DEU => ContinentCode::EU,
            ISO3166Alpha3CountryCode::DJI => ContinentCode::AF,
            ISO3166Alpha3CountryCode::DNK => ContinentCode::EU,
            ISO3166Alpha3CountryCode::DMA => ContinentCode::NA,
            ISO3166Alpha3CountryCode::DOM => ContinentCode::NA,
            ISO3166Alpha3CountryCode::DZA => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ECU => ContinentCode::SA,
            ISO3166Alpha3CountryCode::EST => ContinentCode::EU,
            ISO3166Alpha3CountryCode::EGY => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ESH => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ERI => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ESP => ContinentCode::EU,
            ISO3166Alpha3CountryCode::ETH => ContinentCode::AF,
            ISO3166Alpha3CountryCode::FIN => ContinentCode::EU,
            ISO3166Alpha3CountryCode::FJI => ContinentCode::OC,
            ISO3166Alpha3CountryCode::FLK => ContinentCode::SA,
            ISO3166Alpha3CountryCode::FSM => ContinentCode::OC,
            ISO3166Alpha3CountryCode::FRO => ContinentCode::EU,
            ISO3166Alpha3CountryCode::FRA => ContinentCode::EU,
            ISO3166Alpha3CountryCode::GAB => ContinentCode::AF,
            ISO3166Alpha3CountryCode::GBR => ContinentCode::EU,
            ISO3166Alpha3CountryCode::GRD => ContinentCode::NA,
            ISO3166Alpha3CountryCode::GEO => ContinentCode::AS,
            ISO3166Alpha3CountryCode::GUF => ContinentCode::SA,
            ISO3166Alpha3CountryCode::GGY => ContinentCode::EU,
            ISO3166Alpha3CountryCode::GHA => ContinentCode::AF,
            ISO3166Alpha3CountryCode::GIB => ContinentCode::EU,
            ISO3166Alpha3CountryCode::GRL => ContinentCode::NA,
            ISO3166Alpha3CountryCode::GMB => ContinentCode::AF,
            ISO3166Alpha3CountryCode::GIN => ContinentCode::AF,
            ISO3166Alpha3CountryCode::GLP => ContinentCode::NA,
            ISO3166Alpha3CountryCode::GNQ => ContinentCode::AF,
            ISO3166Alpha3CountryCode::GRC => ContinentCode::EU,
            ISO3166Alpha3CountryCode::SGS => ContinentCode::AN,
            ISO3166Alpha3CountryCode::GTM => ContinentCode::NA,
            ISO3166Alpha3CountryCode::GUM => ContinentCode::OC,
            ISO3166Alpha3CountryCode::GNB => ContinentCode::AF,
            ISO3166Alpha3CountryCode::GUY => ContinentCode::SA,
            ISO3166Alpha3CountryCode::HKG => ContinentCode::AS,
            ISO3166Alpha3CountryCode::HMD => ContinentCode::AN,
            ISO3166Alpha3CountryCode::HND => ContinentCode::NA,
            ISO3166Alpha3CountryCode::HRV => ContinentCode::EU,
            ISO3166Alpha3CountryCode::HTI => ContinentCode::NA,
            ISO3166Alpha3CountryCode::HUN => ContinentCode::EU,
            ISO3166Alpha3CountryCode::IDN => ContinentCode::AS,
            ISO3166Alpha3CountryCode::IRL => ContinentCode::EU,
            ISO3166Alpha3CountryCode::ISR => ContinentCode::AS,
            ISO3166Alpha3CountryCode::IMN => ContinentCode::EU,
            ISO3166Alpha3CountryCode::IND => ContinentCode::AS,
            ISO3166Alpha3CountryCode::IOT => ContinentCode::AS,
            ISO3166Alpha3CountryCode::IRQ => ContinentCode::AS,
            ISO3166Alpha3CountryCode::IRN => ContinentCode::AS,
            ISO3166Alpha3CountryCode::ISL => ContinentCode::EU,
            ISO3166Alpha3CountryCode::ITA => ContinentCode::EU,
            ISO3166Alpha3CountryCode::JEY => ContinentCode::EU,
            ISO3166Alpha3CountryCode::JAM => ContinentCode::NA,
            ISO3166Alpha3CountryCode::JOR => ContinentCode::AS,
            ISO3166Alpha3CountryCode::JPN => ContinentCode::AS,
            ISO3166Alpha3CountryCode::KEN => ContinentCode::AF,
            ISO3166Alpha3CountryCode::KGZ => ContinentCode::AS,
            ISO3166Alpha3CountryCode::KHM => ContinentCode::AS,
            ISO3166Alpha3CountryCode::KIR => ContinentCode::OC,
            ISO3166Alpha3CountryCode::COM => ContinentCode::AF,
            ISO3166Alpha3CountryCode::KNA => ContinentCode::NA,
            ISO3166Alpha3CountryCode::PRK => ContinentCode::AS,
            ISO3166Alpha3CountryCode::KOR => ContinentCode::AS,
            ISO3166Alpha3CountryCode::XKX => ContinentCode::EU,
            ISO3166Alpha3CountryCode::KWT => ContinentCode::AS,
            ISO3166Alpha3CountryCode::CYM => ContinentCode::NA,
            ISO3166Alpha3CountryCode::KAZ => ContinentCode::AS,
            ISO3166Alpha3CountryCode::LAO => ContinentCode::AS,
            ISO3166Alpha3CountryCode::LBN => ContinentCode::AS,
            ISO3166Alpha3CountryCode::LCA => ContinentCode::NA,
            ISO3166Alpha3CountryCode::LIE => ContinentCode::EU,
            ISO3166Alpha3CountryCode::LKA => ContinentCode::AS,
            ISO3166Alpha3CountryCode::LBR => ContinentCode::AF,
            ISO3166Alpha3CountryCode::LSO => ContinentCode::AF,
            ISO3166Alpha3CountryCode::LTU => ContinentCode::EU,
            ISO3166Alpha3CountryCode::LUX => ContinentCode::EU,
            ISO3166Alpha3CountryCode::LVA => ContinentCode::EU,
            ISO3166Alpha3CountryCode::LBY => ContinentCode::AF,
            ISO3166Alpha3CountryCode::MAR => ContinentCode::AF,
            ISO3166Alpha3CountryCode::MCO => ContinentCode::EU,
            ISO3166Alpha3CountryCode::MDA => ContinentCode::EU,
            ISO3166Alpha3CountryCode::MNE => ContinentCode::EU,
            ISO3166Alpha3CountryCode::MAF => ContinentCode::NA,
            ISO3166Alpha3CountryCode::MDG => ContinentCode::AF,
            ISO3166Alpha3CountryCode::MHL => ContinentCode::OC,
            ISO3166Alpha3CountryCode::MKD => ContinentCode::EU,
            ISO3166Alpha3CountryCode::MLI => ContinentCode::AF,
            ISO3166Alpha3CountryCode::MMR => ContinentCode::AS,
            ISO3166Alpha3CountryCode::MNG => ContinentCode::AS,
            ISO3166Alpha3CountryCode::MAC => ContinentCode::AS,
            ISO3166Alpha3CountryCode::MNP => ContinentCode::OC,
            ISO3166Alpha3CountryCode::MTQ => ContinentCode::NA,
            ISO3166Alpha3CountryCode::MRT => ContinentCode::AF,
            ISO3166Alpha3CountryCode::MSR => ContinentCode::NA,
            ISO3166Alpha3CountryCode::MLT => ContinentCode::EU,
            ISO3166Alpha3CountryCode::MUS => ContinentCode::AF,
            ISO3166Alpha3CountryCode::MDV => ContinentCode::AS,
            ISO3166Alpha3CountryCode::MWI => ContinentCode::AF,
            ISO3166Alpha3CountryCode::MEX => ContinentCode::NA,
            ISO3166Alpha3CountryCode::MYS => ContinentCode::AS,
            ISO3166Alpha3CountryCode::MOZ => ContinentCode::AF,
            ISO3166Alpha3CountryCode::NAM => ContinentCode::AF,
            ISO3166Alpha3CountryCode::NCL => ContinentCode::OC,
            ISO3166Alpha3CountryCode::NER => ContinentCode::AF,
            ISO3166Alpha3CountryCode::NFK => ContinentCode::OC,
            ISO3166Alpha3CountryCode::NGA => ContinentCode::AF,
            ISO3166Alpha3CountryCode::NIC => ContinentCode::NA,
            ISO3166Alpha3CountryCode::NLD => ContinentCode::EU,
            ISO3166Alpha3CountryCode::NOR => ContinentCode::EU,
            ISO3166Alpha3CountryCode::NPL => ContinentCode::AS,
            ISO3166Alpha3CountryCode::NRU => ContinentCode::OC,
            ISO3166Alpha3CountryCode::NIU => ContinentCode::OC,
            ISO3166Alpha3CountryCode::NZL => ContinentCode::OC,
            ISO3166Alpha3CountryCode::OMN => ContinentCode::AS,
            ISO3166Alpha3CountryCode::PAN => ContinentCode::NA,
            ISO3166Alpha3CountryCode::PER => ContinentCode::SA,
            ISO3166Alpha3CountryCode::PYF => ContinentCode::OC,
            ISO3166Alpha3CountryCode::PNG => ContinentCode::OC,
            ISO3166Alpha3CountryCode::PHL => ContinentCode::AS,
            ISO3166Alpha3CountryCode::PAK => ContinentCode::AS,
            ISO3166Alpha3CountryCode::POL => ContinentCode::EU,
            ISO3166Alpha3CountryCode::SPM => ContinentCode::NA,
            ISO3166Alpha3CountryCode::PCN => ContinentCode::OC,
            ISO3166Alpha3CountryCode::PRI => ContinentCode::NA,
            ISO3166Alpha3CountryCode::PSE => ContinentCode::AS,
            ISO3166Alpha3CountryCode::PRT => ContinentCode::EU,
            ISO3166Alpha3CountryCode::PLW => ContinentCode::OC,
            ISO3166Alpha3CountryCode::PRY => ContinentCode::SA,
            ISO3166Alpha3CountryCode::QAT => ContinentCode::AS,
            ISO3166Alpha3CountryCode::REU => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ROU => ContinentCode::EU,
            ISO3166Alpha3CountryCode::SRB => ContinentCode::EU,
            ISO3166Alpha3CountryCode::RUS => ContinentCode::EU,
            ISO3166Alpha3CountryCode::RWA => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SAU => ContinentCode::AS,
            ISO3166Alpha3CountryCode::SLB => ContinentCode::OC,
            ISO3166Alpha3CountryCode::SYC => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SDN => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SSD => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SWE => ContinentCode::EU,
            ISO3166Alpha3CountryCode::SGP => ContinentCode::AS,
            ISO3166Alpha3CountryCode::SHN => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SVN => ContinentCode::EU,
            ISO3166Alpha3CountryCode::SJM => ContinentCode::EU,
            ISO3166Alpha3CountryCode::SVK => ContinentCode::EU,
            ISO3166Alpha3CountryCode::SLE => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SMR => ContinentCode::EU,
            ISO3166Alpha3CountryCode::SEN => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SOM => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SUR => ContinentCode::SA,
            ISO3166Alpha3CountryCode::STP => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SLV => ContinentCode::NA,
            ISO3166Alpha3CountryCode::SXM => ContinentCode::NA,
            ISO3166Alpha3CountryCode::SYR => ContinentCode::AS,
            ISO3166Alpha3CountryCode::SWZ => ContinentCode::AF,
            ISO3166Alpha3CountryCode::TCA => ContinentCode::NA,
            ISO3166Alpha3CountryCode::TCD => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ATF => ContinentCode::AN,
            ISO3166Alpha3CountryCode::TGO => ContinentCode::AF,
            ISO3166Alpha3CountryCode::THA => ContinentCode::AS,
            ISO3166Alpha3CountryCode::TJK => ContinentCode::AS,
            ISO3166Alpha3CountryCode::TKL => ContinentCode::OC,
            ISO3166Alpha3CountryCode::TLS => ContinentCode::OC,
            ISO3166Alpha3CountryCode::TKM => ContinentCode::AS,
            ISO3166Alpha3CountryCode::TUN => ContinentCode::AF,
            ISO3166Alpha3CountryCode::TON => ContinentCode::OC,
            ISO3166Alpha3CountryCode::TUR => ContinentCode::AS,
            ISO3166Alpha3CountryCode::TTO => ContinentCode::NA,
            ISO3166Alpha3CountryCode::TUV => ContinentCode::OC,
            ISO3166Alpha3CountryCode::TWN => ContinentCode::AS,
            ISO3166Alpha3CountryCode::TZA => ContinentCode::AF,
            ISO3166Alpha3CountryCode::UKR => ContinentCode::EU,
            ISO3166Alpha3CountryCode::UGA => ContinentCode::AF,
            ISO3166Alpha3CountryCode::UMI => ContinentCode::OC,
            ISO3166Alpha3CountryCode::USA => ContinentCode::NA,
            ISO3166Alpha3CountryCode::URY => ContinentCode::SA,
            ISO3166Alpha3CountryCode::UZB => ContinentCode::AS,
            ISO3166Alpha3CountryCode::VAT => ContinentCode::EU,
            ISO3166Alpha3CountryCode::VCT => ContinentCode::NA,
            ISO3166Alpha3CountryCode::VEN => ContinentCode::SA,
            ISO3166Alpha3CountryCode::VGB => ContinentCode::NA,
            ISO3166Alpha3CountryCode::VIR => ContinentCode::NA,
            ISO3166Alpha3CountryCode::VNM => ContinentCode::AS,
            ISO3166Alpha3CountryCode::VUT => ContinentCode::OC,
            ISO3166Alpha3CountryCode::WLF => ContinentCode::OC,
            ISO3166Alpha3CountryCode::WSM => ContinentCode::OC,
            ISO3166Alpha3CountryCode::YEM => ContinentCode::AS,
            ISO3166Alpha3CountryCode::MYT => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ZAF => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ZMB => ContinentCode::AF,
            ISO3166Alpha3CountryCode::ZWE => ContinentCode::AF,
            ISO3166Alpha3CountryCode::SCG => ContinentCode::EU,
            ISO3166Alpha3CountryCode::ANT => ContinentCode::NA,
        }
    }
}

impl FromStr for ISO3166Alpha3CountryCode {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AND" | "and" => Ok(ISO3166Alpha3CountryCode::AND),
            "ARE" | "are" => Ok(ISO3166Alpha3CountryCode::ARE),
            "AFG" | "afg" => Ok(ISO3166Alpha3CountryCode::AFG),
            "ATG" | "atg" => Ok(ISO3166Alpha3CountryCode::ATG),
            "AIA" | "aia" => Ok(ISO3166Alpha3CountryCode::AIA),
            "ALB" | "alb" => Ok(ISO3166Alpha3CountryCode::ALB),
            "ARM" | "arm" => Ok(ISO3166Alpha3CountryCode::ARM),
            "AGO" | "ago" => Ok(ISO3166Alpha3CountryCode::AGO),
            "ATA" | "ata" => Ok(ISO3166Alpha3CountryCode::ATA),
            "ARG" | "arg" => Ok(ISO3166Alpha3CountryCode::ARG),
            "ASM" | "asm" => Ok(ISO3166Alpha3CountryCode::ASM),
            "AUT" | "aut" => Ok(ISO3166Alpha3CountryCode::AUT),
            "AUS" | "aus" => Ok(ISO3166Alpha3CountryCode::AUS),
            "ABW" | "abw" => Ok(ISO3166Alpha3CountryCode::ABW),
            "ALA" | "ala" => Ok(ISO3166Alpha3CountryCode::ALA),
            "AZE" | "aze" => Ok(ISO3166Alpha3CountryCode::AZE),
            "BIH" | "bih" => Ok(ISO3166Alpha3CountryCode::BIH),
            "BRB" | "brb" => Ok(ISO3166Alpha3CountryCode::BRB),
            "BGD" | "bgd" => Ok(ISO3166Alpha3CountryCode::BGD),
            "BEL" | "bel" => Ok(ISO3166Alpha3CountryCode::BEL),
            "BFA" | "bfa" => Ok(ISO3166Alpha3CountryCode::BFA),
            "BGR" | "bgr" => Ok(ISO3166Alpha3CountryCode::BGR),
            "BHR" | "bhr" => Ok(ISO3166Alpha3CountryCode::BHR),
            "BDI" | "bdi" => Ok(ISO3166Alpha3CountryCode::BDI),
            "BEN" | "ben" => Ok(ISO3166Alpha3CountryCode::BEN),
            "BLM" | "blm" => Ok(ISO3166Alpha3CountryCode::BLM),
            "BMU" | "bmu" => Ok(ISO3166Alpha3CountryCode::BMU),
            "BRN" | "brn" => Ok(ISO3166Alpha3CountryCode::BRN),
            "BOL" | "bol" => Ok(ISO3166Alpha3CountryCode::BOL),
            "BES" | "bes" => Ok(ISO3166Alpha3CountryCode::BES),
            "BRA" | "bra" => Ok(ISO3166Alpha3CountryCode::BRA),
            "BHS" | "bhs" => Ok(ISO3166Alpha3CountryCode::BHS),
            "BTN" | "btn" => Ok(ISO3166Alpha3CountryCode::BTN),
            "BVT" | "bvt" => Ok(ISO3166Alpha3CountryCode::BVT),
            "BWA" | "bwa" => Ok(ISO3166Alpha3CountryCode::BWA),
            "BLR" | "blr" => Ok(ISO3166Alpha3CountryCode::BLR),
            "BLZ" | "blz" => Ok(ISO3166Alpha3CountryCode::BLZ),
            "CAN" | "can" => Ok(ISO3166Alpha3CountryCode::CAN),
            "CCK" | "cck" => Ok(ISO3166Alpha3CountryCode::CCK),
            "COD" | "cod" => Ok(ISO3166Alpha3CountryCode::COD),
            "CAF" | "caf" => Ok(ISO3166Alpha3CountryCode::CAF),
            "COG" | "cog" => Ok(ISO3166Alpha3CountryCode::COG),
            "CHE" | "che" => Ok(ISO3166Alpha3CountryCode::CHE),
            "CIV" | "civ" => Ok(ISO3166Alpha3CountryCode::CIV),
            "COK" | "cok" => Ok(ISO3166Alpha3CountryCode::COK),
            "CHL" | "chl" => Ok(ISO3166Alpha3CountryCode::CHL),
            "CMR" | "cmr" => Ok(ISO3166Alpha3CountryCode::CMR),
            "CHN" | "chn" => Ok(ISO3166Alpha3CountryCode::CHN),
            "COL" | "col" => Ok(ISO3166Alpha3CountryCode::COL),
            "CRI" | "cri" => Ok(ISO3166Alpha3CountryCode::CRI),
            "CUB" | "cub" => Ok(ISO3166Alpha3CountryCode::CUB),
            "CPV" | "cpv" => Ok(ISO3166Alpha3CountryCode::CPV),
            "CUW" | "cuw" => Ok(ISO3166Alpha3CountryCode::CUW),
            "CXR" | "cxr" => Ok(ISO3166Alpha3CountryCode::CXR),
            "CYP" | "cyp" => Ok(ISO3166Alpha3CountryCode::CYP),
            "CZE" | "cze" => Ok(ISO3166Alpha3CountryCode::CZE),
            "DEU" | "deu" => Ok(ISO3166Alpha3CountryCode::DEU),
            "DJI" | "dji" => Ok(ISO3166Alpha3CountryCode::DJI),
            "DNK" | "dnk" => Ok(ISO3166Alpha3CountryCode::DNK),
            "DMA" | "dma" => Ok(ISO3166Alpha3CountryCode::DMA),
            "DOM" | "dom" => Ok(ISO3166Alpha3CountryCode::DOM),
            "DZA" | "dza" => Ok(ISO3166Alpha3CountryCode::DZA),
            "ECU" | "ecu" => Ok(ISO3166Alpha3CountryCode::ECU),
            "EST" | "est" => Ok(ISO3166Alpha3CountryCode::EST),
            "EGY" | "egy" => Ok(ISO3166Alpha3CountryCode::EGY),
            "ESH" | "esh" => Ok(ISO3166Alpha3CountryCode::ESH),
            "ERI" | "eri" => Ok(ISO3166Alpha3CountryCode::ERI),
            "ESP" | "esp" => Ok(ISO3166Alpha3CountryCode::ESP),
            "ETH" | "eth" => Ok(ISO3166Alpha3CountryCode::ETH),
            "FIN" | "fin" => Ok(ISO3166Alpha3CountryCode::FIN),
            "FJI" | "fji" => Ok(ISO3166Alpha3CountryCode::FJI),
            "FLK" | "flk" => Ok(ISO3166Alpha3CountryCode::FLK),
            "FSM" | "fsm" => Ok(ISO3166Alpha3CountryCode::FSM),
            "FRO" | "fro" => Ok(ISO3166Alpha3CountryCode::FRO),
            "FRA" | "fra" => Ok(ISO3166Alpha3CountryCode::FRA),
            "GAB" | "gab" => Ok(ISO3166Alpha3CountryCode::GAB),
            "GBR" | "gbr" => Ok(ISO3166Alpha3CountryCode::GBR),
            "GRD" | "grd" => Ok(ISO3166Alpha3CountryCode::GRD),
            "GEO" | "geo" => Ok(ISO3166Alpha3CountryCode::GEO),
            "GUF" | "guf" => Ok(ISO3166Alpha3CountryCode::GUF),
            "GGY" | "ggy" => Ok(ISO3166Alpha3CountryCode::GGY),
            "GHA" | "gha" => Ok(ISO3166Alpha3CountryCode::GHA),
            "GIB" | "gib" => Ok(ISO3166Alpha3CountryCode::GIB),
            "GRL" | "grl" => Ok(ISO3166Alpha3CountryCode::GRL),
            "GMB" | "gmb" => Ok(ISO3166Alpha3CountryCode::GMB),
            "GIN" | "gin" => Ok(ISO3166Alpha3CountryCode::GIN),
            "GLP" | "glp" => Ok(ISO3166Alpha3CountryCode::GLP),
            "GNQ" | "gnq" => Ok(ISO3166Alpha3CountryCode::GNQ),
            "GRC" | "grc" => Ok(ISO3166Alpha3CountryCode::GRC),
            "SGS" | "sgs" => Ok(ISO3166Alpha3CountryCode::SGS),
            "GTM" | "gtm" => Ok(ISO3166Alpha3CountryCode::GTM),
            "GUM" | "gum" => Ok(ISO3166Alpha3CountryCode::GUM),
            "GNB" | "gnb" => Ok(ISO3166Alpha3CountryCode::GNB),
            "GUY" | "guy" => Ok(ISO3166Alpha3CountryCode::GUY),
            "HKG" | "hkg" => Ok(ISO3166Alpha3CountryCode::HKG),
            "HMD" | "hmd" => Ok(ISO3166Alpha3CountryCode::HMD),
            "HND" | "hnd" => Ok(ISO3166Alpha3CountryCode::HND),
            "HRV" | "hrv" => Ok(ISO3166Alpha3CountryCode::HRV),
            "HTI" | "hti" => Ok(ISO3166Alpha3CountryCode::HTI),
            "HUN" | "hun" => Ok(ISO3166Alpha3CountryCode::HUN),
            "IDN" | "idn" => Ok(ISO3166Alpha3CountryCode::IDN),
            "IRL" | "irl" => Ok(ISO3166Alpha3CountryCode::IRL),
            "ISR" | "isr" => Ok(ISO3166Alpha3CountryCode::ISR),
            "IMN" | "imn" => Ok(ISO3166Alpha3CountryCode::IMN),
            "IND" | "ind" => Ok(ISO3166Alpha3CountryCode::IND),
            "IOT" | "iot" => Ok(ISO3166Alpha3CountryCode::IOT),
            "IRQ" | "irq" => Ok(ISO3166Alpha3CountryCode::IRQ),
            "IRN" | "irn" => Ok(ISO3166Alpha3CountryCode::IRN),
            "ISL" | "isl" => Ok(ISO3166Alpha3CountryCode::ISL),
            "ITA" | "ita" => Ok(ISO3166Alpha3CountryCode::ITA),
            "JEY" | "jey" => Ok(ISO3166Alpha3CountryCode::JEY),
            "JAM" | "jam" => Ok(ISO3166Alpha3CountryCode::JAM),
            "JOR" | "jor" => Ok(ISO3166Alpha3CountryCode::JOR),
            "JPN" | "jpn" => Ok(ISO3166Alpha3CountryCode::JPN),
            "KEN" | "ken" => Ok(ISO3166Alpha3CountryCode::KEN),
            "KGZ" | "kgz" => Ok(ISO3166Alpha3CountryCode::KGZ),
            "KHM" | "khm" => Ok(ISO3166Alpha3CountryCode::KHM),
            "KIR" | "kir" => Ok(ISO3166Alpha3CountryCode::KIR),
            "COM" | "com" => Ok(ISO3166Alpha3CountryCode::COM),
            "KNA" | "kna" => Ok(ISO3166Alpha3CountryCode::KNA),
            "PRK" | "prk" => Ok(ISO3166Alpha3CountryCode::PRK),
            "KOR" | "kor" => Ok(ISO3166Alpha3CountryCode::KOR),
            "XKX" | "xkx" => Ok(ISO3166Alpha3CountryCode::XKX),
            "KWT" | "kwt" => Ok(ISO3166Alpha3CountryCode::KWT),
            "CYM" | "cym" => Ok(ISO3166Alpha3CountryCode::CYM),
            "KAZ" | "kaz" => Ok(ISO3166Alpha3CountryCode::KAZ),
            "LAO" | "lao" => Ok(ISO3166Alpha3CountryCode::LAO),
            "LBN" | "lbn" => Ok(ISO3166Alpha3CountryCode::LBN),
            "LCA" | "lca" => Ok(ISO3166Alpha3CountryCode::LCA),
            "LIE" | "lie" => Ok(ISO3166Alpha3CountryCode::LIE),
            "LKA" | "lka" => Ok(ISO3166Alpha3CountryCode::LKA),
            "LBR" | "lbr" => Ok(ISO3166Alpha3CountryCode::LBR),
            "LSO" | "lso" => Ok(ISO3166Alpha3CountryCode::LSO),
            "LTU" | "ltu" => Ok(ISO3166Alpha3CountryCode::LTU),
            "LUX" | "lux" => Ok(ISO3166Alpha3CountryCode::LUX),
            "LVA" | "lva" => Ok(ISO3166Alpha3CountryCode::LVA),
            "LBY" | "lby" => Ok(ISO3166Alpha3CountryCode::LBY),
            "MAR" | "mar" => Ok(ISO3166Alpha3CountryCode::MAR),
            "MCO" | "mco" => Ok(ISO3166Alpha3CountryCode::MCO),
            "MDA" | "mda" => Ok(ISO3166Alpha3CountryCode::MDA),
            "MNE" | "mne" => Ok(ISO3166Alpha3CountryCode::MNE),
            "MAF" | "maf" => Ok(ISO3166Alpha3CountryCode::MAF),
            "MDG" | "mdg" => Ok(ISO3166Alpha3CountryCode::MDG),
            "MHL" | "mhl" => Ok(ISO3166Alpha3CountryCode::MHL),
            "MKD" | "mkd" => Ok(ISO3166Alpha3CountryCode::MKD),
            "MLI" | "mli" => Ok(ISO3166Alpha3CountryCode::MLI),
            "MMR" | "mmr" => Ok(ISO3166Alpha3CountryCode::MMR),
            "MNG" | "mng" => Ok(ISO3166Alpha3CountryCode::MNG),
            "MAC" | "mac" => Ok(ISO3166Alpha3CountryCode::MAC),
            "MNP" | "mnp" => Ok(ISO3166Alpha3CountryCode::MNP),
            "MTQ" | "mtq" => Ok(ISO3166Alpha3CountryCode::MTQ),
            "MRT" | "mrt" => Ok(ISO3166Alpha3CountryCode::MRT),
            "MSR" | "msr" => Ok(ISO3166Alpha3CountryCode::MSR),
            "MLT" | "mlt" => Ok(ISO3166Alpha3CountryCode::MLT),
            "MUS" | "mus" => Ok(ISO3166Alpha3CountryCode::MUS),
            "MDV" | "mdv" => Ok(ISO3166Alpha3CountryCode::MDV),
            "MWI" | "mwi" => Ok(ISO3166Alpha3CountryCode::MWI),
            "MEX" | "mex" => Ok(ISO3166Alpha3CountryCode::MEX),
            "MYS" | "mys" => Ok(ISO3166Alpha3CountryCode::MYS),
            "MOZ" | "moz" => Ok(ISO3166Alpha3CountryCode::MOZ),
            "NAM" | "nam" => Ok(ISO3166Alpha3CountryCode::NAM),
            "NCL" | "ncl" => Ok(ISO3166Alpha3CountryCode::NCL),
            "NER" | "ner" => Ok(ISO3166Alpha3CountryCode::NER),
            "NFK" | "nfk" => Ok(ISO3166Alpha3CountryCode::NFK),
            "NGA" | "nga" => Ok(ISO3166Alpha3CountryCode::NGA),
            "NIC" | "nic" => Ok(ISO3166Alpha3CountryCode::NIC),
            "NLD" | "nld" => Ok(ISO3166Alpha3CountryCode::NLD),
            "NOR" | "nor" => Ok(ISO3166Alpha3CountryCode::NOR),
            "NPL" | "npl" => Ok(ISO3166Alpha3CountryCode::NPL),
            "NRU" | "nru" => Ok(ISO3166Alpha3CountryCode::NRU),
            "NIU" | "niu" => Ok(ISO3166Alpha3CountryCode::NIU),
            "NZL" | "nzl" => Ok(ISO3166Alpha3CountryCode::NZL),
            "OMN" | "omn" => Ok(ISO3166Alpha3CountryCode::OMN),
            "PAN" | "pan" => Ok(ISO3166Alpha3CountryCode::PAN),
            "PER" | "per" => Ok(ISO3166Alpha3CountryCode::PER),
            "PYF" | "pyf" => Ok(ISO3166Alpha3CountryCode::PYF),
            "PNG" | "png" => Ok(ISO3166Alpha3CountryCode::PNG),
            "PHL" | "phl" => Ok(ISO3166Alpha3CountryCode::PHL),
            "PAK" | "pak" => Ok(ISO3166Alpha3CountryCode::PAK),
            "POL" | "pol" => Ok(ISO3166Alpha3CountryCode::POL),
            "SPM" | "spm" => Ok(ISO3166Alpha3CountryCode::SPM),
            "PCN" | "pcn" => Ok(ISO3166Alpha3CountryCode::PCN),
            "PRI" | "pri" => Ok(ISO3166Alpha3CountryCode::PRI),
            "PSE" | "pse" => Ok(ISO3166Alpha3CountryCode::PSE),
            "PRT" | "prt" => Ok(ISO3166Alpha3CountryCode::PRT),
            "PLW" | "plw" => Ok(ISO3166Alpha3CountryCode::PLW),
            "PRY" | "pry" => Ok(ISO3166Alpha3CountryCode::PRY),
            "QAT" | "qat" => Ok(ISO3166Alpha3CountryCode::QAT),
            "REU" | "reu" => Ok(ISO3166Alpha3CountryCode::REU),
            "ROU" | "rou" => Ok(ISO3166Alpha3CountryCode::ROU),
            "SRB" | "srb" => Ok(ISO3166Alpha3CountryCode::SRB),
            "RUS" | "rus" => Ok(ISO3166Alpha3CountryCode::RUS),
            "RWA" | "rwa" => Ok(ISO3166Alpha3CountryCode::RWA),
            "SAU" | "sau" => Ok(ISO3166Alpha3CountryCode::SAU),
            "SLB" | "slb" => Ok(ISO3166Alpha3CountryCode::SLB),
            "SYC" | "syc" => Ok(ISO3166Alpha3CountryCode::SYC),
            "SDN" | "sdn" => Ok(ISO3166Alpha3CountryCode::SDN),
            "SSD" | "ssd" => Ok(ISO3166Alpha3CountryCode::SSD),
            "SWE" | "swe" => Ok(ISO3166Alpha3CountryCode::SWE),
            "SGP" | "sgp" => Ok(ISO3166Alpha3CountryCode::SGP),
            "SHN" | "shn" => Ok(ISO3166Alpha3CountryCode::SHN),
            "SVN" | "svn" => Ok(ISO3166Alpha3CountryCode::SVN),
            "SJM" | "sjm" => Ok(ISO3166Alpha3CountryCode::SJM),
            "SVK" | "svk" => Ok(ISO3166Alpha3CountryCode::SVK),
            "SLE" | "sle" => Ok(ISO3166Alpha3CountryCode::SLE),
            "SMR" | "smr" => Ok(ISO3166Alpha3CountryCode::SMR),
            "SEN" | "sen" => Ok(ISO3166Alpha3CountryCode::SEN),
            "SOM" | "som" => Ok(ISO3166Alpha3CountryCode::SOM),
            "SUR" | "sur" => Ok(ISO3166Alpha3CountryCode::SUR),
            "STP" | "stp" => Ok(ISO3166Alpha3CountryCode::STP),
            "SLV" | "slv" => Ok(ISO3166Alpha3CountryCode::SLV),
            "SXM" | "sxm" => Ok(ISO3166Alpha3CountryCode::SXM),
            "SYR" | "syr" => Ok(ISO3166Alpha3CountryCode::SYR),
            "SWZ" | "swz" => Ok(ISO3166Alpha3CountryCode::SWZ),
            "TCA" | "tca" => Ok(ISO3166Alpha3CountryCode::TCA),
            "TCD" | "tcd" => Ok(ISO3166Alpha3CountryCode::TCD),
            "ATF" | "atf" => Ok(ISO3166Alpha3CountryCode::ATF),
            "TGO" | "tgo" => Ok(ISO3166Alpha3CountryCode::TGO),
            "THA" | "tha" => Ok(ISO3166Alpha3CountryCode::THA),
            "TJK" | "tjk" => Ok(ISO3166Alpha3CountryCode::TJK),
            "TKL" | "tkl" => Ok(ISO3166Alpha3CountryCode::TKL),
            "TLS" | "tls" => Ok(ISO3166Alpha3CountryCode::TLS),
            "TKM" | "tkm" => Ok(ISO3166Alpha3CountryCode::TKM),
            "TUN" | "tun" => Ok(ISO3166Alpha3CountryCode::TUN),
            "TON" | "ton" => Ok(ISO3166Alpha3CountryCode::TON),
            "TUR" | "tur" => Ok(ISO3166Alpha3CountryCode::TUR),
            "TTO" | "tto" => Ok(ISO3166Alpha3CountryCode::TTO),
            "TUV" | "tuv" => Ok(ISO3166Alpha3CountryCode::TUV),
            "TWN" | "twn" => Ok(ISO3166Alpha3CountryCode::TWN),
            "TZA" | "tza" => Ok(ISO3166Alpha3CountryCode::TZA),
            "UKR" | "ukr" => Ok(ISO3166Alpha3CountryCode::UKR),
            "UGA" | "uga" => Ok(ISO3166Alpha3CountryCode::UGA),
            "UMI" | "umi" => Ok(ISO3166Alpha3CountryCode::UMI),
            "USA" | "usa" => Ok(ISO3166Alpha3CountryCode::USA),
            "URY" | "ury" => Ok(ISO3166Alpha3CountryCode::URY),
            "UZB" | "uzb" => Ok(ISO3166Alpha3CountryCode::UZB),
            "VAT" | "vat" => Ok(ISO3166Alpha3CountryCode::VAT),
            "VCT" | "vct" => Ok(ISO3166Alpha3CountryCode::VCT),
            "VEN" | "ven" => Ok(ISO3166Alpha3CountryCode::VEN),
            "VGB" | "vgb" => Ok(ISO3166Alpha3CountryCode::VGB),
            "VIR" | "vir" => Ok(ISO3166Alpha3CountryCode::VIR),
            "VNM" | "vnm" => Ok(ISO3166Alpha3CountryCode::VNM),
            "VUT" | "vut" => Ok(ISO3166Alpha3CountryCode::VUT),
            "WLF" | "wlf" => Ok(ISO3166Alpha3CountryCode::WLF),
            "WSM" | "wsm" => Ok(ISO3166Alpha3CountryCode::WSM),
            "YEM" | "yem" => Ok(ISO3166Alpha3CountryCode::YEM),
            "MYT" | "myt" => Ok(ISO3166Alpha3CountryCode::MYT),
            "ZAF" | "zaf" => Ok(ISO3166Alpha3CountryCode::ZAF),
            "ZMB" | "zmb" => Ok(ISO3166Alpha3CountryCode::ZMB),
            "ZWE" | "zwe" => Ok(ISO3166Alpha3CountryCode::ZWE),
            "SCG" | "scg" => Ok(ISO3166Alpha3CountryCode::SCG),
            "ANT" | "ant" => Ok(ISO3166Alpha3CountryCode::ANT),
            _ => Err(()),
        }
    }
}
