/*
 * Copyright 2023 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

///
/// This file is auto generated by scripts/generate/country/convert.sh,
/// by using the data from https://download.geonames.org/export/dump/countryInfo.txt
///
use std::str::FromStr;

use crate::ContinentCode;

const ALL_COUNTRY_NAMES: &[&str] = &[
    "Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua and Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Angola",
    "Antarctica",
    "Argentina",
    "American Samoa",
    "Austria",
    "Australia",
    "Aruba",
    "Aland Islands",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Saint Barthelemy",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Bonaire, Saint Eustatius and Saba ",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cocos Islands",
    "Democratic Republic of the Congo",
    "Central African Republic",
    "Republic of the Congo",
    "Switzerland",
    "Ivory Coast",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curacao",
    "Christmas Island",
    "Cyprus",
    "Czechia",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Western Sahara",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Micronesia",
    "Faroe Islands",
    "France",
    "Gabon",
    "United Kingdom",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Equatorial Guinea",
    "Greece",
    "South Georgia and the South Sandwich Islands",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hong Kong",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "British Indian Ocean Territory",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "Saint Kitts and Nevis",
    "North Korea",
    "South Korea",
    "Kosovo",
    "Kuwait",
    "Cayman Islands",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "Marshall Islands",
    "North Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Northern Mariana Islands",
    "Martinique",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre and Miquelon",
    "Pitcairn",
    "Puerto Rico",
    "Palestinian Territory",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Reunion",
    "Romania",
    "Serbia",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "South Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena",
    "Slovenia",
    "Svalbard and Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "Sao Tome and Principe",
    "El Salvador",
    "Sint Maarten",
    "Syria",
    "Eswatini",
    "Turks and Caicos Islands",
    "Chad",
    "French Southern Territories",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "Timor Leste",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "United States Minor Outlying Islands",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vatican",
    "Saint Vincent and the Grenadines",
    "Venezuela",
    "British Virgin Islands",
    "U.S. Virgin Islands",
    "Vietnam",
    "Vanuatu",
    "Wallis and Futuna",
    "Samoa",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe",
    "Serbia and Montenegro",
    "Netherlands Antilles",
];

const ALL_ALPHA2_CODES: &[&str] = &[
    "AD", /* Andorra */
    "AE", /* United Arab Emirates */
    "AF", /* Afghanistan */
    "AG", /* Antigua and Barbuda */
    "AI", /* Anguilla */
    "AL", /* Albania */
    "AM", /* Armenia */
    "AO", /* Angola */
    "AQ", /* Antarctica */
    "AR", /* Argentina */
    "AS", /* American Samoa */
    "AT", /* Austria */
    "AU", /* Australia */
    "AW", /* Aruba */
    "AX", /* Aland Islands */
    "AZ", /* Azerbaijan */
    "BA", /* Bosnia and Herzegovina */
    "BB", /* Barbados */
    "BD", /* Bangladesh */
    "BE", /* Belgium */
    "BF", /* Burkina Faso */
    "BG", /* Bulgaria */
    "BH", /* Bahrain */
    "BI", /* Burundi */
    "BJ", /* Benin */
    "BL", /* Saint Barthelemy */
    "BM", /* Bermuda */
    "BN", /* Brunei */
    "BO", /* Bolivia */
    "BQ", /* Bonaire, Saint Eustatius and Saba  */
    "BR", /* Brazil */
    "BS", /* Bahamas */
    "BT", /* Bhutan */
    "BV", /* Bouvet Island */
    "BW", /* Botswana */
    "BY", /* Belarus */
    "BZ", /* Belize */
    "CA", /* Canada */
    "CC", /* Cocos Islands */
    "CD", /* Democratic Republic of the Congo */
    "CF", /* Central African Republic */
    "CG", /* Republic of the Congo */
    "CH", /* Switzerland */
    "CI", /* Ivory Coast */
    "CK", /* Cook Islands */
    "CL", /* Chile */
    "CM", /* Cameroon */
    "CN", /* China */
    "CO", /* Colombia */
    "CR", /* Costa Rica */
    "CU", /* Cuba */
    "CV", /* Cabo Verde */
    "CW", /* Curacao */
    "CX", /* Christmas Island */
    "CY", /* Cyprus */
    "CZ", /* Czechia */
    "DE", /* Germany */
    "DJ", /* Djibouti */
    "DK", /* Denmark */
    "DM", /* Dominica */
    "DO", /* Dominican Republic */
    "DZ", /* Algeria */
    "EC", /* Ecuador */
    "EE", /* Estonia */
    "EG", /* Egypt */
    "EH", /* Western Sahara */
    "ER", /* Eritrea */
    "ES", /* Spain */
    "ET", /* Ethiopia */
    "FI", /* Finland */
    "FJ", /* Fiji */
    "FK", /* Falkland Islands */
    "FM", /* Micronesia */
    "FO", /* Faroe Islands */
    "FR", /* France */
    "GA", /* Gabon */
    "GB", /* United Kingdom */
    "GD", /* Grenada */
    "GE", /* Georgia */
    "GF", /* French Guiana */
    "GG", /* Guernsey */
    "GH", /* Ghana */
    "GI", /* Gibraltar */
    "GL", /* Greenland */
    "GM", /* Gambia */
    "GN", /* Guinea */
    "GP", /* Guadeloupe */
    "GQ", /* Equatorial Guinea */
    "GR", /* Greece */
    "GS", /* South Georgia and the South Sandwich Islands */
    "GT", /* Guatemala */
    "GU", /* Guam */
    "GW", /* Guinea-Bissau */
    "GY", /* Guyana */
    "HK", /* Hong Kong */
    "HM", /* Heard Island and McDonald Islands */
    "HN", /* Honduras */
    "HR", /* Croatia */
    "HT", /* Haiti */
    "HU", /* Hungary */
    "ID", /* Indonesia */
    "IE", /* Ireland */
    "IL", /* Israel */
    "IM", /* Isle of Man */
    "IN", /* India */
    "IO", /* British Indian Ocean Territory */
    "IQ", /* Iraq */
    "IR", /* Iran */
    "IS", /* Iceland */
    "IT", /* Italy */
    "JE", /* Jersey */
    "JM", /* Jamaica */
    "JO", /* Jordan */
    "JP", /* Japan */
    "KE", /* Kenya */
    "KG", /* Kyrgyzstan */
    "KH", /* Cambodia */
    "KI", /* Kiribati */
    "KM", /* Comoros */
    "KN", /* Saint Kitts and Nevis */
    "KP", /* North Korea */
    "KR", /* South Korea */
    "XK", /* Kosovo */
    "KW", /* Kuwait */
    "KY", /* Cayman Islands */
    "KZ", /* Kazakhstan */
    "LA", /* Laos */
    "LB", /* Lebanon */
    "LC", /* Saint Lucia */
    "LI", /* Liechtenstein */
    "LK", /* Sri Lanka */
    "LR", /* Liberia */
    "LS", /* Lesotho */
    "LT", /* Lithuania */
    "LU", /* Luxembourg */
    "LV", /* Latvia */
    "LY", /* Libya */
    "MA", /* Morocco */
    "MC", /* Monaco */
    "MD", /* Moldova */
    "ME", /* Montenegro */
    "MF", /* Saint Martin */
    "MG", /* Madagascar */
    "MH", /* Marshall Islands */
    "MK", /* North Macedonia */
    "ML", /* Mali */
    "MM", /* Myanmar */
    "MN", /* Mongolia */
    "MO", /* Macao */
    "MP", /* Northern Mariana Islands */
    "MQ", /* Martinique */
    "MR", /* Mauritania */
    "MS", /* Montserrat */
    "MT", /* Malta */
    "MU", /* Mauritius */
    "MV", /* Maldives */
    "MW", /* Malawi */
    "MX", /* Mexico */
    "MY", /* Malaysia */
    "MZ", /* Mozambique */
    "NA", /* Namibia */
    "NC", /* New Caledonia */
    "NE", /* Niger */
    "NF", /* Norfolk Island */
    "NG", /* Nigeria */
    "NI", /* Nicaragua */
    "NL", /* Netherlands */
    "NO", /* Norway */
    "NP", /* Nepal */
    "NR", /* Nauru */
    "NU", /* Niue */
    "NZ", /* New Zealand */
    "OM", /* Oman */
    "PA", /* Panama */
    "PE", /* Peru */
    "PF", /* French Polynesia */
    "PG", /* Papua New Guinea */
    "PH", /* Philippines */
    "PK", /* Pakistan */
    "PL", /* Poland */
    "PM", /* Saint Pierre and Miquelon */
    "PN", /* Pitcairn */
    "PR", /* Puerto Rico */
    "PS", /* Palestinian Territory */
    "PT", /* Portugal */
    "PW", /* Palau */
    "PY", /* Paraguay */
    "QA", /* Qatar */
    "RE", /* Reunion */
    "RO", /* Romania */
    "RS", /* Serbia */
    "RU", /* Russia */
    "RW", /* Rwanda */
    "SA", /* Saudi Arabia */
    "SB", /* Solomon Islands */
    "SC", /* Seychelles */
    "SD", /* Sudan */
    "SS", /* South Sudan */
    "SE", /* Sweden */
    "SG", /* Singapore */
    "SH", /* Saint Helena */
    "SI", /* Slovenia */
    "SJ", /* Svalbard and Jan Mayen */
    "SK", /* Slovakia */
    "SL", /* Sierra Leone */
    "SM", /* San Marino */
    "SN", /* Senegal */
    "SO", /* Somalia */
    "SR", /* Suriname */
    "ST", /* Sao Tome and Principe */
    "SV", /* El Salvador */
    "SX", /* Sint Maarten */
    "SY", /* Syria */
    "SZ", /* Eswatini */
    "TC", /* Turks and Caicos Islands */
    "TD", /* Chad */
    "TF", /* French Southern Territories */
    "TG", /* Togo */
    "TH", /* Thailand */
    "TJ", /* Tajikistan */
    "TK", /* Tokelau */
    "TL", /* Timor Leste */
    "TM", /* Turkmenistan */
    "TN", /* Tunisia */
    "TO", /* Tonga */
    "TR", /* Turkey */
    "TT", /* Trinidad and Tobago */
    "TV", /* Tuvalu */
    "TW", /* Taiwan */
    "TZ", /* Tanzania */
    "UA", /* Ukraine */
    "UG", /* Uganda */
    "UM", /* United States Minor Outlying Islands */
    "US", /* United States */
    "UY", /* Uruguay */
    "UZ", /* Uzbekistan */
    "VA", /* Vatican */
    "VC", /* Saint Vincent and the Grenadines */
    "VE", /* Venezuela */
    "VG", /* British Virgin Islands */
    "VI", /* U.S. Virgin Islands */
    "VN", /* Vietnam */
    "VU", /* Vanuatu */
    "WF", /* Wallis and Futuna */
    "WS", /* Samoa */
    "YE", /* Yemen */
    "YT", /* Mayotte */
    "ZA", /* South Africa */
    "ZM", /* Zambia */
    "ZW", /* Zimbabwe */
    "CS", /* Serbia and Montenegro */
    "AN", /* Netherlands Antilles */
];

const ALL_ALPHA3_CODES: &[&str] = &[
    "AND", /* Andorra */
    "ARE", /* United Arab Emirates */
    "AFG", /* Afghanistan */
    "ATG", /* Antigua and Barbuda */
    "AIA", /* Anguilla */
    "ALB", /* Albania */
    "ARM", /* Armenia */
    "AGO", /* Angola */
    "ATA", /* Antarctica */
    "ARG", /* Argentina */
    "ASM", /* American Samoa */
    "AUT", /* Austria */
    "AUS", /* Australia */
    "ABW", /* Aruba */
    "ALA", /* Aland Islands */
    "AZE", /* Azerbaijan */
    "BIH", /* Bosnia and Herzegovina */
    "BRB", /* Barbados */
    "BGD", /* Bangladesh */
    "BEL", /* Belgium */
    "BFA", /* Burkina Faso */
    "BGR", /* Bulgaria */
    "BHR", /* Bahrain */
    "BDI", /* Burundi */
    "BEN", /* Benin */
    "BLM", /* Saint Barthelemy */
    "BMU", /* Bermuda */
    "BRN", /* Brunei */
    "BOL", /* Bolivia */
    "BES", /* Bonaire, Saint Eustatius and Saba  */
    "BRA", /* Brazil */
    "BHS", /* Bahamas */
    "BTN", /* Bhutan */
    "BVT", /* Bouvet Island */
    "BWA", /* Botswana */
    "BLR", /* Belarus */
    "BLZ", /* Belize */
    "CAN", /* Canada */
    "CCK", /* Cocos Islands */
    "COD", /* Democratic Republic of the Congo */
    "CAF", /* Central African Republic */
    "COG", /* Republic of the Congo */
    "CHE", /* Switzerland */
    "CIV", /* Ivory Coast */
    "COK", /* Cook Islands */
    "CHL", /* Chile */
    "CMR", /* Cameroon */
    "CHN", /* China */
    "COL", /* Colombia */
    "CRI", /* Costa Rica */
    "CUB", /* Cuba */
    "CPV", /* Cabo Verde */
    "CUW", /* Curacao */
    "CXR", /* Christmas Island */
    "CYP", /* Cyprus */
    "CZE", /* Czechia */
    "DEU", /* Germany */
    "DJI", /* Djibouti */
    "DNK", /* Denmark */
    "DMA", /* Dominica */
    "DOM", /* Dominican Republic */
    "DZA", /* Algeria */
    "ECU", /* Ecuador */
    "EST", /* Estonia */
    "EGY", /* Egypt */
    "ESH", /* Western Sahara */
    "ERI", /* Eritrea */
    "ESP", /* Spain */
    "ETH", /* Ethiopia */
    "FIN", /* Finland */
    "FJI", /* Fiji */
    "FLK", /* Falkland Islands */
    "FSM", /* Micronesia */
    "FRO", /* Faroe Islands */
    "FRA", /* France */
    "GAB", /* Gabon */
    "GBR", /* United Kingdom */
    "GRD", /* Grenada */
    "GEO", /* Georgia */
    "GUF", /* French Guiana */
    "GGY", /* Guernsey */
    "GHA", /* Ghana */
    "GIB", /* Gibraltar */
    "GRL", /* Greenland */
    "GMB", /* Gambia */
    "GIN", /* Guinea */
    "GLP", /* Guadeloupe */
    "GNQ", /* Equatorial Guinea */
    "GRC", /* Greece */
    "SGS", /* South Georgia and the South Sandwich Islands */
    "GTM", /* Guatemala */
    "GUM", /* Guam */
    "GNB", /* Guinea-Bissau */
    "GUY", /* Guyana */
    "HKG", /* Hong Kong */
    "HMD", /* Heard Island and McDonald Islands */
    "HND", /* Honduras */
    "HRV", /* Croatia */
    "HTI", /* Haiti */
    "HUN", /* Hungary */
    "IDN", /* Indonesia */
    "IRL", /* Ireland */
    "ISR", /* Israel */
    "IMN", /* Isle of Man */
    "IND", /* India */
    "IOT", /* British Indian Ocean Territory */
    "IRQ", /* Iraq */
    "IRN", /* Iran */
    "ISL", /* Iceland */
    "ITA", /* Italy */
    "JEY", /* Jersey */
    "JAM", /* Jamaica */
    "JOR", /* Jordan */
    "JPN", /* Japan */
    "KEN", /* Kenya */
    "KGZ", /* Kyrgyzstan */
    "KHM", /* Cambodia */
    "KIR", /* Kiribati */
    "COM", /* Comoros */
    "KNA", /* Saint Kitts and Nevis */
    "PRK", /* North Korea */
    "KOR", /* South Korea */
    "XKX", /* Kosovo */
    "KWT", /* Kuwait */
    "CYM", /* Cayman Islands */
    "KAZ", /* Kazakhstan */
    "LAO", /* Laos */
    "LBN", /* Lebanon */
    "LCA", /* Saint Lucia */
    "LIE", /* Liechtenstein */
    "LKA", /* Sri Lanka */
    "LBR", /* Liberia */
    "LSO", /* Lesotho */
    "LTU", /* Lithuania */
    "LUX", /* Luxembourg */
    "LVA", /* Latvia */
    "LBY", /* Libya */
    "MAR", /* Morocco */
    "MCO", /* Monaco */
    "MDA", /* Moldova */
    "MNE", /* Montenegro */
    "MAF", /* Saint Martin */
    "MDG", /* Madagascar */
    "MHL", /* Marshall Islands */
    "MKD", /* North Macedonia */
    "MLI", /* Mali */
    "MMR", /* Myanmar */
    "MNG", /* Mongolia */
    "MAC", /* Macao */
    "MNP", /* Northern Mariana Islands */
    "MTQ", /* Martinique */
    "MRT", /* Mauritania */
    "MSR", /* Montserrat */
    "MLT", /* Malta */
    "MUS", /* Mauritius */
    "MDV", /* Maldives */
    "MWI", /* Malawi */
    "MEX", /* Mexico */
    "MYS", /* Malaysia */
    "MOZ", /* Mozambique */
    "NAM", /* Namibia */
    "NCL", /* New Caledonia */
    "NER", /* Niger */
    "NFK", /* Norfolk Island */
    "NGA", /* Nigeria */
    "NIC", /* Nicaragua */
    "NLD", /* Netherlands */
    "NOR", /* Norway */
    "NPL", /* Nepal */
    "NRU", /* Nauru */
    "NIU", /* Niue */
    "NZL", /* New Zealand */
    "OMN", /* Oman */
    "PAN", /* Panama */
    "PER", /* Peru */
    "PYF", /* French Polynesia */
    "PNG", /* Papua New Guinea */
    "PHL", /* Philippines */
    "PAK", /* Pakistan */
    "POL", /* Poland */
    "SPM", /* Saint Pierre and Miquelon */
    "PCN", /* Pitcairn */
    "PRI", /* Puerto Rico */
    "PSE", /* Palestinian Territory */
    "PRT", /* Portugal */
    "PLW", /* Palau */
    "PRY", /* Paraguay */
    "QAT", /* Qatar */
    "REU", /* Reunion */
    "ROU", /* Romania */
    "SRB", /* Serbia */
    "RUS", /* Russia */
    "RWA", /* Rwanda */
    "SAU", /* Saudi Arabia */
    "SLB", /* Solomon Islands */
    "SYC", /* Seychelles */
    "SDN", /* Sudan */
    "SSD", /* South Sudan */
    "SWE", /* Sweden */
    "SGP", /* Singapore */
    "SHN", /* Saint Helena */
    "SVN", /* Slovenia */
    "SJM", /* Svalbard and Jan Mayen */
    "SVK", /* Slovakia */
    "SLE", /* Sierra Leone */
    "SMR", /* San Marino */
    "SEN", /* Senegal */
    "SOM", /* Somalia */
    "SUR", /* Suriname */
    "STP", /* Sao Tome and Principe */
    "SLV", /* El Salvador */
    "SXM", /* Sint Maarten */
    "SYR", /* Syria */
    "SWZ", /* Eswatini */
    "TCA", /* Turks and Caicos Islands */
    "TCD", /* Chad */
    "ATF", /* French Southern Territories */
    "TGO", /* Togo */
    "THA", /* Thailand */
    "TJK", /* Tajikistan */
    "TKL", /* Tokelau */
    "TLS", /* Timor Leste */
    "TKM", /* Turkmenistan */
    "TUN", /* Tunisia */
    "TON", /* Tonga */
    "TUR", /* Turkey */
    "TTO", /* Trinidad and Tobago */
    "TUV", /* Tuvalu */
    "TWN", /* Taiwan */
    "TZA", /* Tanzania */
    "UKR", /* Ukraine */
    "UGA", /* Uganda */
    "UMI", /* United States Minor Outlying Islands */
    "USA", /* United States */
    "URY", /* Uruguay */
    "UZB", /* Uzbekistan */
    "VAT", /* Vatican */
    "VCT", /* Saint Vincent and the Grenadines */
    "VEN", /* Venezuela */
    "VGB", /* British Virgin Islands */
    "VIR", /* U.S. Virgin Islands */
    "VNM", /* Vietnam */
    "VUT", /* Vanuatu */
    "WLF", /* Wallis and Futuna */
    "WSM", /* Samoa */
    "YEM", /* Yemen */
    "MYT", /* Mayotte */
    "ZAF", /* South Africa */
    "ZMB", /* Zambia */
    "ZWE", /* Zimbabwe */
    "SCG", /* Serbia and Montenegro */
    "ANT", /* Netherlands Antilles */
];

#[derive(Debug, Clone, Copy)]
pub enum IsoCountryCode {
    AD, /* AND - Andorra */
    AE, /* ARE - United Arab Emirates */
    AF, /* AFG - Afghanistan */
    AG, /* ATG - Antigua and Barbuda */
    AI, /* AIA - Anguilla */
    AL, /* ALB - Albania */
    AM, /* ARM - Armenia */
    AO, /* AGO - Angola */
    AQ, /* ATA - Antarctica */
    AR, /* ARG - Argentina */
    AS, /* ASM - American Samoa */
    AT, /* AUT - Austria */
    AU, /* AUS - Australia */
    AW, /* ABW - Aruba */
    AX, /* ALA - Aland Islands */
    AZ, /* AZE - Azerbaijan */
    BA, /* BIH - Bosnia and Herzegovina */
    BB, /* BRB - Barbados */
    BD, /* BGD - Bangladesh */
    BE, /* BEL - Belgium */
    BF, /* BFA - Burkina Faso */
    BG, /* BGR - Bulgaria */
    BH, /* BHR - Bahrain */
    BI, /* BDI - Burundi */
    BJ, /* BEN - Benin */
    BL, /* BLM - Saint Barthelemy */
    BM, /* BMU - Bermuda */
    BN, /* BRN - Brunei */
    BO, /* BOL - Bolivia */
    BQ, /* BES - Bonaire, Saint Eustatius and Saba  */
    BR, /* BRA - Brazil */
    BS, /* BHS - Bahamas */
    BT, /* BTN - Bhutan */
    BV, /* BVT - Bouvet Island */
    BW, /* BWA - Botswana */
    BY, /* BLR - Belarus */
    BZ, /* BLZ - Belize */
    CA, /* CAN - Canada */
    CC, /* CCK - Cocos Islands */
    CD, /* COD - Democratic Republic of the Congo */
    CF, /* CAF - Central African Republic */
    CG, /* COG - Republic of the Congo */
    CH, /* CHE - Switzerland */
    CI, /* CIV - Ivory Coast */
    CK, /* COK - Cook Islands */
    CL, /* CHL - Chile */
    CM, /* CMR - Cameroon */
    CN, /* CHN - China */
    CO, /* COL - Colombia */
    CR, /* CRI - Costa Rica */
    CU, /* CUB - Cuba */
    CV, /* CPV - Cabo Verde */
    CW, /* CUW - Curacao */
    CX, /* CXR - Christmas Island */
    CY, /* CYP - Cyprus */
    CZ, /* CZE - Czechia */
    DE, /* DEU - Germany */
    DJ, /* DJI - Djibouti */
    DK, /* DNK - Denmark */
    DM, /* DMA - Dominica */
    DO, /* DOM - Dominican Republic */
    DZ, /* DZA - Algeria */
    EC, /* ECU - Ecuador */
    EE, /* EST - Estonia */
    EG, /* EGY - Egypt */
    EH, /* ESH - Western Sahara */
    ER, /* ERI - Eritrea */
    ES, /* ESP - Spain */
    ET, /* ETH - Ethiopia */
    FI, /* FIN - Finland */
    FJ, /* FJI - Fiji */
    FK, /* FLK - Falkland Islands */
    FM, /* FSM - Micronesia */
    FO, /* FRO - Faroe Islands */
    FR, /* FRA - France */
    GA, /* GAB - Gabon */
    GB, /* GBR - United Kingdom */
    GD, /* GRD - Grenada */
    GE, /* GEO - Georgia */
    GF, /* GUF - French Guiana */
    GG, /* GGY - Guernsey */
    GH, /* GHA - Ghana */
    GI, /* GIB - Gibraltar */
    GL, /* GRL - Greenland */
    GM, /* GMB - Gambia */
    GN, /* GIN - Guinea */
    GP, /* GLP - Guadeloupe */
    GQ, /* GNQ - Equatorial Guinea */
    GR, /* GRC - Greece */
    GS, /* SGS - South Georgia and the South Sandwich Islands */
    GT, /* GTM - Guatemala */
    GU, /* GUM - Guam */
    GW, /* GNB - Guinea-Bissau */
    GY, /* GUY - Guyana */
    HK, /* HKG - Hong Kong */
    HM, /* HMD - Heard Island and McDonald Islands */
    HN, /* HND - Honduras */
    HR, /* HRV - Croatia */
    HT, /* HTI - Haiti */
    HU, /* HUN - Hungary */
    ID, /* IDN - Indonesia */
    IE, /* IRL - Ireland */
    IL, /* ISR - Israel */
    IM, /* IMN - Isle of Man */
    IN, /* IND - India */
    IO, /* IOT - British Indian Ocean Territory */
    IQ, /* IRQ - Iraq */
    IR, /* IRN - Iran */
    IS, /* ISL - Iceland */
    IT, /* ITA - Italy */
    JE, /* JEY - Jersey */
    JM, /* JAM - Jamaica */
    JO, /* JOR - Jordan */
    JP, /* JPN - Japan */
    KE, /* KEN - Kenya */
    KG, /* KGZ - Kyrgyzstan */
    KH, /* KHM - Cambodia */
    KI, /* KIR - Kiribati */
    KM, /* COM - Comoros */
    KN, /* KNA - Saint Kitts and Nevis */
    KP, /* PRK - North Korea */
    KR, /* KOR - South Korea */
    XK, /* XKX - Kosovo */
    KW, /* KWT - Kuwait */
    KY, /* CYM - Cayman Islands */
    KZ, /* KAZ - Kazakhstan */
    LA, /* LAO - Laos */
    LB, /* LBN - Lebanon */
    LC, /* LCA - Saint Lucia */
    LI, /* LIE - Liechtenstein */
    LK, /* LKA - Sri Lanka */
    LR, /* LBR - Liberia */
    LS, /* LSO - Lesotho */
    LT, /* LTU - Lithuania */
    LU, /* LUX - Luxembourg */
    LV, /* LVA - Latvia */
    LY, /* LBY - Libya */
    MA, /* MAR - Morocco */
    MC, /* MCO - Monaco */
    MD, /* MDA - Moldova */
    ME, /* MNE - Montenegro */
    MF, /* MAF - Saint Martin */
    MG, /* MDG - Madagascar */
    MH, /* MHL - Marshall Islands */
    MK, /* MKD - North Macedonia */
    ML, /* MLI - Mali */
    MM, /* MMR - Myanmar */
    MN, /* MNG - Mongolia */
    MO, /* MAC - Macao */
    MP, /* MNP - Northern Mariana Islands */
    MQ, /* MTQ - Martinique */
    MR, /* MRT - Mauritania */
    MS, /* MSR - Montserrat */
    MT, /* MLT - Malta */
    MU, /* MUS - Mauritius */
    MV, /* MDV - Maldives */
    MW, /* MWI - Malawi */
    MX, /* MEX - Mexico */
    MY, /* MYS - Malaysia */
    MZ, /* MOZ - Mozambique */
    NA, /* NAM - Namibia */
    NC, /* NCL - New Caledonia */
    NE, /* NER - Niger */
    NF, /* NFK - Norfolk Island */
    NG, /* NGA - Nigeria */
    NI, /* NIC - Nicaragua */
    NL, /* NLD - Netherlands */
    NO, /* NOR - Norway */
    NP, /* NPL - Nepal */
    NR, /* NRU - Nauru */
    NU, /* NIU - Niue */
    NZ, /* NZL - New Zealand */
    OM, /* OMN - Oman */
    PA, /* PAN - Panama */
    PE, /* PER - Peru */
    PF, /* PYF - French Polynesia */
    PG, /* PNG - Papua New Guinea */
    PH, /* PHL - Philippines */
    PK, /* PAK - Pakistan */
    PL, /* POL - Poland */
    PM, /* SPM - Saint Pierre and Miquelon */
    PN, /* PCN - Pitcairn */
    PR, /* PRI - Puerto Rico */
    PS, /* PSE - Palestinian Territory */
    PT, /* PRT - Portugal */
    PW, /* PLW - Palau */
    PY, /* PRY - Paraguay */
    QA, /* QAT - Qatar */
    RE, /* REU - Reunion */
    RO, /* ROU - Romania */
    RS, /* SRB - Serbia */
    RU, /* RUS - Russia */
    RW, /* RWA - Rwanda */
    SA, /* SAU - Saudi Arabia */
    SB, /* SLB - Solomon Islands */
    SC, /* SYC - Seychelles */
    SD, /* SDN - Sudan */
    SS, /* SSD - South Sudan */
    SE, /* SWE - Sweden */
    SG, /* SGP - Singapore */
    SH, /* SHN - Saint Helena */
    SI, /* SVN - Slovenia */
    SJ, /* SJM - Svalbard and Jan Mayen */
    SK, /* SVK - Slovakia */
    SL, /* SLE - Sierra Leone */
    SM, /* SMR - San Marino */
    SN, /* SEN - Senegal */
    SO, /* SOM - Somalia */
    SR, /* SUR - Suriname */
    ST, /* STP - Sao Tome and Principe */
    SV, /* SLV - El Salvador */
    SX, /* SXM - Sint Maarten */
    SY, /* SYR - Syria */
    SZ, /* SWZ - Eswatini */
    TC, /* TCA - Turks and Caicos Islands */
    TD, /* TCD - Chad */
    TF, /* ATF - French Southern Territories */
    TG, /* TGO - Togo */
    TH, /* THA - Thailand */
    TJ, /* TJK - Tajikistan */
    TK, /* TKL - Tokelau */
    TL, /* TLS - Timor Leste */
    TM, /* TKM - Turkmenistan */
    TN, /* TUN - Tunisia */
    TO, /* TON - Tonga */
    TR, /* TUR - Turkey */
    TT, /* TTO - Trinidad and Tobago */
    TV, /* TUV - Tuvalu */
    TW, /* TWN - Taiwan */
    TZ, /* TZA - Tanzania */
    UA, /* UKR - Ukraine */
    UG, /* UGA - Uganda */
    UM, /* UMI - United States Minor Outlying Islands */
    US, /* USA - United States */
    UY, /* URY - Uruguay */
    UZ, /* UZB - Uzbekistan */
    VA, /* VAT - Vatican */
    VC, /* VCT - Saint Vincent and the Grenadines */
    VE, /* VEN - Venezuela */
    VG, /* VGB - British Virgin Islands */
    VI, /* VIR - U.S. Virgin Islands */
    VN, /* VNM - Vietnam */
    VU, /* VUT - Vanuatu */
    WF, /* WLF - Wallis and Futuna */
    WS, /* WSM - Samoa */
    YE, /* YEM - Yemen */
    YT, /* MYT - Mayotte */
    ZA, /* ZAF - South Africa */
    ZM, /* ZMB - Zambia */
    ZW, /* ZWE - Zimbabwe */
    CS, /* SCG - Serbia and Montenegro */
    AN, /* ANT - Netherlands Antilles */
}

impl IsoCountryCode {
    pub fn name(&self) -> &'static str {
        ALL_COUNTRY_NAMES[*self as usize]
    }

    pub fn alpha2_code(&self) -> &'static str {
        ALL_ALPHA2_CODES[*self as usize]
    }

    pub fn alpha3_code(&self) -> &'static str {
        ALL_ALPHA3_CODES[*self as usize]
    }

    pub fn continent(&self) -> ContinentCode {
        match self {
            IsoCountryCode::AD => ContinentCode::EU,
            IsoCountryCode::AE => ContinentCode::AS,
            IsoCountryCode::AF => ContinentCode::AS,
            IsoCountryCode::AG => ContinentCode::NA,
            IsoCountryCode::AI => ContinentCode::NA,
            IsoCountryCode::AL => ContinentCode::EU,
            IsoCountryCode::AM => ContinentCode::AS,
            IsoCountryCode::AO => ContinentCode::AF,
            IsoCountryCode::AQ => ContinentCode::AN,
            IsoCountryCode::AR => ContinentCode::SA,
            IsoCountryCode::AS => ContinentCode::OC,
            IsoCountryCode::AT => ContinentCode::EU,
            IsoCountryCode::AU => ContinentCode::OC,
            IsoCountryCode::AW => ContinentCode::NA,
            IsoCountryCode::AX => ContinentCode::EU,
            IsoCountryCode::AZ => ContinentCode::AS,
            IsoCountryCode::BA => ContinentCode::EU,
            IsoCountryCode::BB => ContinentCode::NA,
            IsoCountryCode::BD => ContinentCode::AS,
            IsoCountryCode::BE => ContinentCode::EU,
            IsoCountryCode::BF => ContinentCode::AF,
            IsoCountryCode::BG => ContinentCode::EU,
            IsoCountryCode::BH => ContinentCode::AS,
            IsoCountryCode::BI => ContinentCode::AF,
            IsoCountryCode::BJ => ContinentCode::AF,
            IsoCountryCode::BL => ContinentCode::NA,
            IsoCountryCode::BM => ContinentCode::NA,
            IsoCountryCode::BN => ContinentCode::AS,
            IsoCountryCode::BO => ContinentCode::SA,
            IsoCountryCode::BQ => ContinentCode::NA,
            IsoCountryCode::BR => ContinentCode::SA,
            IsoCountryCode::BS => ContinentCode::NA,
            IsoCountryCode::BT => ContinentCode::AS,
            IsoCountryCode::BV => ContinentCode::AN,
            IsoCountryCode::BW => ContinentCode::AF,
            IsoCountryCode::BY => ContinentCode::EU,
            IsoCountryCode::BZ => ContinentCode::NA,
            IsoCountryCode::CA => ContinentCode::NA,
            IsoCountryCode::CC => ContinentCode::AS,
            IsoCountryCode::CD => ContinentCode::AF,
            IsoCountryCode::CF => ContinentCode::AF,
            IsoCountryCode::CG => ContinentCode::AF,
            IsoCountryCode::CH => ContinentCode::EU,
            IsoCountryCode::CI => ContinentCode::AF,
            IsoCountryCode::CK => ContinentCode::OC,
            IsoCountryCode::CL => ContinentCode::SA,
            IsoCountryCode::CM => ContinentCode::AF,
            IsoCountryCode::CN => ContinentCode::AS,
            IsoCountryCode::CO => ContinentCode::SA,
            IsoCountryCode::CR => ContinentCode::NA,
            IsoCountryCode::CU => ContinentCode::NA,
            IsoCountryCode::CV => ContinentCode::AF,
            IsoCountryCode::CW => ContinentCode::NA,
            IsoCountryCode::CX => ContinentCode::OC,
            IsoCountryCode::CY => ContinentCode::EU,
            IsoCountryCode::CZ => ContinentCode::EU,
            IsoCountryCode::DE => ContinentCode::EU,
            IsoCountryCode::DJ => ContinentCode::AF,
            IsoCountryCode::DK => ContinentCode::EU,
            IsoCountryCode::DM => ContinentCode::NA,
            IsoCountryCode::DO => ContinentCode::NA,
            IsoCountryCode::DZ => ContinentCode::AF,
            IsoCountryCode::EC => ContinentCode::SA,
            IsoCountryCode::EE => ContinentCode::EU,
            IsoCountryCode::EG => ContinentCode::AF,
            IsoCountryCode::EH => ContinentCode::AF,
            IsoCountryCode::ER => ContinentCode::AF,
            IsoCountryCode::ES => ContinentCode::EU,
            IsoCountryCode::ET => ContinentCode::AF,
            IsoCountryCode::FI => ContinentCode::EU,
            IsoCountryCode::FJ => ContinentCode::OC,
            IsoCountryCode::FK => ContinentCode::SA,
            IsoCountryCode::FM => ContinentCode::OC,
            IsoCountryCode::FO => ContinentCode::EU,
            IsoCountryCode::FR => ContinentCode::EU,
            IsoCountryCode::GA => ContinentCode::AF,
            IsoCountryCode::GB => ContinentCode::EU,
            IsoCountryCode::GD => ContinentCode::NA,
            IsoCountryCode::GE => ContinentCode::AS,
            IsoCountryCode::GF => ContinentCode::SA,
            IsoCountryCode::GG => ContinentCode::EU,
            IsoCountryCode::GH => ContinentCode::AF,
            IsoCountryCode::GI => ContinentCode::EU,
            IsoCountryCode::GL => ContinentCode::NA,
            IsoCountryCode::GM => ContinentCode::AF,
            IsoCountryCode::GN => ContinentCode::AF,
            IsoCountryCode::GP => ContinentCode::NA,
            IsoCountryCode::GQ => ContinentCode::AF,
            IsoCountryCode::GR => ContinentCode::EU,
            IsoCountryCode::GS => ContinentCode::AN,
            IsoCountryCode::GT => ContinentCode::NA,
            IsoCountryCode::GU => ContinentCode::OC,
            IsoCountryCode::GW => ContinentCode::AF,
            IsoCountryCode::GY => ContinentCode::SA,
            IsoCountryCode::HK => ContinentCode::AS,
            IsoCountryCode::HM => ContinentCode::AN,
            IsoCountryCode::HN => ContinentCode::NA,
            IsoCountryCode::HR => ContinentCode::EU,
            IsoCountryCode::HT => ContinentCode::NA,
            IsoCountryCode::HU => ContinentCode::EU,
            IsoCountryCode::ID => ContinentCode::AS,
            IsoCountryCode::IE => ContinentCode::EU,
            IsoCountryCode::IL => ContinentCode::AS,
            IsoCountryCode::IM => ContinentCode::EU,
            IsoCountryCode::IN => ContinentCode::AS,
            IsoCountryCode::IO => ContinentCode::AS,
            IsoCountryCode::IQ => ContinentCode::AS,
            IsoCountryCode::IR => ContinentCode::AS,
            IsoCountryCode::IS => ContinentCode::EU,
            IsoCountryCode::IT => ContinentCode::EU,
            IsoCountryCode::JE => ContinentCode::EU,
            IsoCountryCode::JM => ContinentCode::NA,
            IsoCountryCode::JO => ContinentCode::AS,
            IsoCountryCode::JP => ContinentCode::AS,
            IsoCountryCode::KE => ContinentCode::AF,
            IsoCountryCode::KG => ContinentCode::AS,
            IsoCountryCode::KH => ContinentCode::AS,
            IsoCountryCode::KI => ContinentCode::OC,
            IsoCountryCode::KM => ContinentCode::AF,
            IsoCountryCode::KN => ContinentCode::NA,
            IsoCountryCode::KP => ContinentCode::AS,
            IsoCountryCode::KR => ContinentCode::AS,
            IsoCountryCode::XK => ContinentCode::EU,
            IsoCountryCode::KW => ContinentCode::AS,
            IsoCountryCode::KY => ContinentCode::NA,
            IsoCountryCode::KZ => ContinentCode::AS,
            IsoCountryCode::LA => ContinentCode::AS,
            IsoCountryCode::LB => ContinentCode::AS,
            IsoCountryCode::LC => ContinentCode::NA,
            IsoCountryCode::LI => ContinentCode::EU,
            IsoCountryCode::LK => ContinentCode::AS,
            IsoCountryCode::LR => ContinentCode::AF,
            IsoCountryCode::LS => ContinentCode::AF,
            IsoCountryCode::LT => ContinentCode::EU,
            IsoCountryCode::LU => ContinentCode::EU,
            IsoCountryCode::LV => ContinentCode::EU,
            IsoCountryCode::LY => ContinentCode::AF,
            IsoCountryCode::MA => ContinentCode::AF,
            IsoCountryCode::MC => ContinentCode::EU,
            IsoCountryCode::MD => ContinentCode::EU,
            IsoCountryCode::ME => ContinentCode::EU,
            IsoCountryCode::MF => ContinentCode::NA,
            IsoCountryCode::MG => ContinentCode::AF,
            IsoCountryCode::MH => ContinentCode::OC,
            IsoCountryCode::MK => ContinentCode::EU,
            IsoCountryCode::ML => ContinentCode::AF,
            IsoCountryCode::MM => ContinentCode::AS,
            IsoCountryCode::MN => ContinentCode::AS,
            IsoCountryCode::MO => ContinentCode::AS,
            IsoCountryCode::MP => ContinentCode::OC,
            IsoCountryCode::MQ => ContinentCode::NA,
            IsoCountryCode::MR => ContinentCode::AF,
            IsoCountryCode::MS => ContinentCode::NA,
            IsoCountryCode::MT => ContinentCode::EU,
            IsoCountryCode::MU => ContinentCode::AF,
            IsoCountryCode::MV => ContinentCode::AS,
            IsoCountryCode::MW => ContinentCode::AF,
            IsoCountryCode::MX => ContinentCode::NA,
            IsoCountryCode::MY => ContinentCode::AS,
            IsoCountryCode::MZ => ContinentCode::AF,
            IsoCountryCode::NA => ContinentCode::AF,
            IsoCountryCode::NC => ContinentCode::OC,
            IsoCountryCode::NE => ContinentCode::AF,
            IsoCountryCode::NF => ContinentCode::OC,
            IsoCountryCode::NG => ContinentCode::AF,
            IsoCountryCode::NI => ContinentCode::NA,
            IsoCountryCode::NL => ContinentCode::EU,
            IsoCountryCode::NO => ContinentCode::EU,
            IsoCountryCode::NP => ContinentCode::AS,
            IsoCountryCode::NR => ContinentCode::OC,
            IsoCountryCode::NU => ContinentCode::OC,
            IsoCountryCode::NZ => ContinentCode::OC,
            IsoCountryCode::OM => ContinentCode::AS,
            IsoCountryCode::PA => ContinentCode::NA,
            IsoCountryCode::PE => ContinentCode::SA,
            IsoCountryCode::PF => ContinentCode::OC,
            IsoCountryCode::PG => ContinentCode::OC,
            IsoCountryCode::PH => ContinentCode::AS,
            IsoCountryCode::PK => ContinentCode::AS,
            IsoCountryCode::PL => ContinentCode::EU,
            IsoCountryCode::PM => ContinentCode::NA,
            IsoCountryCode::PN => ContinentCode::OC,
            IsoCountryCode::PR => ContinentCode::NA,
            IsoCountryCode::PS => ContinentCode::AS,
            IsoCountryCode::PT => ContinentCode::EU,
            IsoCountryCode::PW => ContinentCode::OC,
            IsoCountryCode::PY => ContinentCode::SA,
            IsoCountryCode::QA => ContinentCode::AS,
            IsoCountryCode::RE => ContinentCode::AF,
            IsoCountryCode::RO => ContinentCode::EU,
            IsoCountryCode::RS => ContinentCode::EU,
            IsoCountryCode::RU => ContinentCode::EU,
            IsoCountryCode::RW => ContinentCode::AF,
            IsoCountryCode::SA => ContinentCode::AS,
            IsoCountryCode::SB => ContinentCode::OC,
            IsoCountryCode::SC => ContinentCode::AF,
            IsoCountryCode::SD => ContinentCode::AF,
            IsoCountryCode::SS => ContinentCode::AF,
            IsoCountryCode::SE => ContinentCode::EU,
            IsoCountryCode::SG => ContinentCode::AS,
            IsoCountryCode::SH => ContinentCode::AF,
            IsoCountryCode::SI => ContinentCode::EU,
            IsoCountryCode::SJ => ContinentCode::EU,
            IsoCountryCode::SK => ContinentCode::EU,
            IsoCountryCode::SL => ContinentCode::AF,
            IsoCountryCode::SM => ContinentCode::EU,
            IsoCountryCode::SN => ContinentCode::AF,
            IsoCountryCode::SO => ContinentCode::AF,
            IsoCountryCode::SR => ContinentCode::SA,
            IsoCountryCode::ST => ContinentCode::AF,
            IsoCountryCode::SV => ContinentCode::NA,
            IsoCountryCode::SX => ContinentCode::NA,
            IsoCountryCode::SY => ContinentCode::AS,
            IsoCountryCode::SZ => ContinentCode::AF,
            IsoCountryCode::TC => ContinentCode::NA,
            IsoCountryCode::TD => ContinentCode::AF,
            IsoCountryCode::TF => ContinentCode::AN,
            IsoCountryCode::TG => ContinentCode::AF,
            IsoCountryCode::TH => ContinentCode::AS,
            IsoCountryCode::TJ => ContinentCode::AS,
            IsoCountryCode::TK => ContinentCode::OC,
            IsoCountryCode::TL => ContinentCode::OC,
            IsoCountryCode::TM => ContinentCode::AS,
            IsoCountryCode::TN => ContinentCode::AF,
            IsoCountryCode::TO => ContinentCode::OC,
            IsoCountryCode::TR => ContinentCode::AS,
            IsoCountryCode::TT => ContinentCode::NA,
            IsoCountryCode::TV => ContinentCode::OC,
            IsoCountryCode::TW => ContinentCode::AS,
            IsoCountryCode::TZ => ContinentCode::AF,
            IsoCountryCode::UA => ContinentCode::EU,
            IsoCountryCode::UG => ContinentCode::AF,
            IsoCountryCode::UM => ContinentCode::OC,
            IsoCountryCode::US => ContinentCode::NA,
            IsoCountryCode::UY => ContinentCode::SA,
            IsoCountryCode::UZ => ContinentCode::AS,
            IsoCountryCode::VA => ContinentCode::EU,
            IsoCountryCode::VC => ContinentCode::NA,
            IsoCountryCode::VE => ContinentCode::SA,
            IsoCountryCode::VG => ContinentCode::NA,
            IsoCountryCode::VI => ContinentCode::NA,
            IsoCountryCode::VN => ContinentCode::AS,
            IsoCountryCode::VU => ContinentCode::OC,
            IsoCountryCode::WF => ContinentCode::OC,
            IsoCountryCode::WS => ContinentCode::OC,
            IsoCountryCode::YE => ContinentCode::AS,
            IsoCountryCode::YT => ContinentCode::AF,
            IsoCountryCode::ZA => ContinentCode::AF,
            IsoCountryCode::ZM => ContinentCode::AF,
            IsoCountryCode::ZW => ContinentCode::AF,
            IsoCountryCode::CS => ContinentCode::EU,
            IsoCountryCode::AN => ContinentCode::NA,
        }
    }
}

impl FromStr for IsoCountryCode {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.len() {
            2 => match s {
                "AD" | "ad" => Ok(IsoCountryCode::AD),
                "AE" | "ae" => Ok(IsoCountryCode::AE),
                "AF" | "af" => Ok(IsoCountryCode::AF),
                "AG" | "ag" => Ok(IsoCountryCode::AG),
                "AI" | "ai" => Ok(IsoCountryCode::AI),
                "AL" | "al" => Ok(IsoCountryCode::AL),
                "AM" | "am" => Ok(IsoCountryCode::AM),
                "AO" | "ao" => Ok(IsoCountryCode::AO),
                "AQ" | "aq" => Ok(IsoCountryCode::AQ),
                "AR" | "ar" => Ok(IsoCountryCode::AR),
                "AS" | "as" => Ok(IsoCountryCode::AS),
                "AT" | "at" => Ok(IsoCountryCode::AT),
                "AU" | "au" => Ok(IsoCountryCode::AU),
                "AW" | "aw" => Ok(IsoCountryCode::AW),
                "AX" | "ax" => Ok(IsoCountryCode::AX),
                "AZ" | "az" => Ok(IsoCountryCode::AZ),
                "BA" | "ba" => Ok(IsoCountryCode::BA),
                "BB" | "bb" => Ok(IsoCountryCode::BB),
                "BD" | "bd" => Ok(IsoCountryCode::BD),
                "BE" | "be" => Ok(IsoCountryCode::BE),
                "BF" | "bf" => Ok(IsoCountryCode::BF),
                "BG" | "bg" => Ok(IsoCountryCode::BG),
                "BH" | "bh" => Ok(IsoCountryCode::BH),
                "BI" | "bi" => Ok(IsoCountryCode::BI),
                "BJ" | "bj" => Ok(IsoCountryCode::BJ),
                "BL" | "bl" => Ok(IsoCountryCode::BL),
                "BM" | "bm" => Ok(IsoCountryCode::BM),
                "BN" | "bn" => Ok(IsoCountryCode::BN),
                "BO" | "bo" => Ok(IsoCountryCode::BO),
                "BQ" | "bq" => Ok(IsoCountryCode::BQ),
                "BR" | "br" => Ok(IsoCountryCode::BR),
                "BS" | "bs" => Ok(IsoCountryCode::BS),
                "BT" | "bt" => Ok(IsoCountryCode::BT),
                "BV" | "bv" => Ok(IsoCountryCode::BV),
                "BW" | "bw" => Ok(IsoCountryCode::BW),
                "BY" | "by" => Ok(IsoCountryCode::BY),
                "BZ" | "bz" => Ok(IsoCountryCode::BZ),
                "CA" | "ca" => Ok(IsoCountryCode::CA),
                "CC" | "cc" => Ok(IsoCountryCode::CC),
                "CD" | "cd" => Ok(IsoCountryCode::CD),
                "CF" | "cf" => Ok(IsoCountryCode::CF),
                "CG" | "cg" => Ok(IsoCountryCode::CG),
                "CH" | "ch" => Ok(IsoCountryCode::CH),
                "CI" | "ci" => Ok(IsoCountryCode::CI),
                "CK" | "ck" => Ok(IsoCountryCode::CK),
                "CL" | "cl" => Ok(IsoCountryCode::CL),
                "CM" | "cm" => Ok(IsoCountryCode::CM),
                "CN" | "cn" => Ok(IsoCountryCode::CN),
                "CO" | "co" => Ok(IsoCountryCode::CO),
                "CR" | "cr" => Ok(IsoCountryCode::CR),
                "CU" | "cu" => Ok(IsoCountryCode::CU),
                "CV" | "cv" => Ok(IsoCountryCode::CV),
                "CW" | "cw" => Ok(IsoCountryCode::CW),
                "CX" | "cx" => Ok(IsoCountryCode::CX),
                "CY" | "cy" => Ok(IsoCountryCode::CY),
                "CZ" | "cz" => Ok(IsoCountryCode::CZ),
                "DE" | "de" => Ok(IsoCountryCode::DE),
                "DJ" | "dj" => Ok(IsoCountryCode::DJ),
                "DK" | "dk" => Ok(IsoCountryCode::DK),
                "DM" | "dm" => Ok(IsoCountryCode::DM),
                "DO" | "do" => Ok(IsoCountryCode::DO),
                "DZ" | "dz" => Ok(IsoCountryCode::DZ),
                "EC" | "ec" => Ok(IsoCountryCode::EC),
                "EE" | "ee" => Ok(IsoCountryCode::EE),
                "EG" | "eg" => Ok(IsoCountryCode::EG),
                "EH" | "eh" => Ok(IsoCountryCode::EH),
                "ER" | "er" => Ok(IsoCountryCode::ER),
                "ES" | "es" => Ok(IsoCountryCode::ES),
                "ET" | "et" => Ok(IsoCountryCode::ET),
                "FI" | "fi" => Ok(IsoCountryCode::FI),
                "FJ" | "fj" => Ok(IsoCountryCode::FJ),
                "FK" | "fk" => Ok(IsoCountryCode::FK),
                "FM" | "fm" => Ok(IsoCountryCode::FM),
                "FO" | "fo" => Ok(IsoCountryCode::FO),
                "FR" | "fr" => Ok(IsoCountryCode::FR),
                "GA" | "ga" => Ok(IsoCountryCode::GA),
                "GB" | "gb" => Ok(IsoCountryCode::GB),
                "GD" | "gd" => Ok(IsoCountryCode::GD),
                "GE" | "ge" => Ok(IsoCountryCode::GE),
                "GF" | "gf" => Ok(IsoCountryCode::GF),
                "GG" | "gg" => Ok(IsoCountryCode::GG),
                "GH" | "gh" => Ok(IsoCountryCode::GH),
                "GI" | "gi" => Ok(IsoCountryCode::GI),
                "GL" | "gl" => Ok(IsoCountryCode::GL),
                "GM" | "gm" => Ok(IsoCountryCode::GM),
                "GN" | "gn" => Ok(IsoCountryCode::GN),
                "GP" | "gp" => Ok(IsoCountryCode::GP),
                "GQ" | "gq" => Ok(IsoCountryCode::GQ),
                "GR" | "gr" => Ok(IsoCountryCode::GR),
                "GS" | "gs" => Ok(IsoCountryCode::GS),
                "GT" | "gt" => Ok(IsoCountryCode::GT),
                "GU" | "gu" => Ok(IsoCountryCode::GU),
                "GW" | "gw" => Ok(IsoCountryCode::GW),
                "GY" | "gy" => Ok(IsoCountryCode::GY),
                "HK" | "hk" => Ok(IsoCountryCode::HK),
                "HM" | "hm" => Ok(IsoCountryCode::HM),
                "HN" | "hn" => Ok(IsoCountryCode::HN),
                "HR" | "hr" => Ok(IsoCountryCode::HR),
                "HT" | "ht" => Ok(IsoCountryCode::HT),
                "HU" | "hu" => Ok(IsoCountryCode::HU),
                "ID" | "id" => Ok(IsoCountryCode::ID),
                "IE" | "ie" => Ok(IsoCountryCode::IE),
                "IL" | "il" => Ok(IsoCountryCode::IL),
                "IM" | "im" => Ok(IsoCountryCode::IM),
                "IN" | "in" => Ok(IsoCountryCode::IN),
                "IO" | "io" => Ok(IsoCountryCode::IO),
                "IQ" | "iq" => Ok(IsoCountryCode::IQ),
                "IR" | "ir" => Ok(IsoCountryCode::IR),
                "IS" | "is" => Ok(IsoCountryCode::IS),
                "IT" | "it" => Ok(IsoCountryCode::IT),
                "JE" | "je" => Ok(IsoCountryCode::JE),
                "JM" | "jm" => Ok(IsoCountryCode::JM),
                "JO" | "jo" => Ok(IsoCountryCode::JO),
                "JP" | "jp" => Ok(IsoCountryCode::JP),
                "KE" | "ke" => Ok(IsoCountryCode::KE),
                "KG" | "kg" => Ok(IsoCountryCode::KG),
                "KH" | "kh" => Ok(IsoCountryCode::KH),
                "KI" | "ki" => Ok(IsoCountryCode::KI),
                "KM" | "km" => Ok(IsoCountryCode::KM),
                "KN" | "kn" => Ok(IsoCountryCode::KN),
                "KP" | "kp" => Ok(IsoCountryCode::KP),
                "KR" | "kr" => Ok(IsoCountryCode::KR),
                "XK" | "xk" => Ok(IsoCountryCode::XK),
                "KW" | "kw" => Ok(IsoCountryCode::KW),
                "KY" | "ky" => Ok(IsoCountryCode::KY),
                "KZ" | "kz" => Ok(IsoCountryCode::KZ),
                "LA" | "la" => Ok(IsoCountryCode::LA),
                "LB" | "lb" => Ok(IsoCountryCode::LB),
                "LC" | "lc" => Ok(IsoCountryCode::LC),
                "LI" | "li" => Ok(IsoCountryCode::LI),
                "LK" | "lk" => Ok(IsoCountryCode::LK),
                "LR" | "lr" => Ok(IsoCountryCode::LR),
                "LS" | "ls" => Ok(IsoCountryCode::LS),
                "LT" | "lt" => Ok(IsoCountryCode::LT),
                "LU" | "lu" => Ok(IsoCountryCode::LU),
                "LV" | "lv" => Ok(IsoCountryCode::LV),
                "LY" | "ly" => Ok(IsoCountryCode::LY),
                "MA" | "ma" => Ok(IsoCountryCode::MA),
                "MC" | "mc" => Ok(IsoCountryCode::MC),
                "MD" | "md" => Ok(IsoCountryCode::MD),
                "ME" | "me" => Ok(IsoCountryCode::ME),
                "MF" | "mf" => Ok(IsoCountryCode::MF),
                "MG" | "mg" => Ok(IsoCountryCode::MG),
                "MH" | "mh" => Ok(IsoCountryCode::MH),
                "MK" | "mk" => Ok(IsoCountryCode::MK),
                "ML" | "ml" => Ok(IsoCountryCode::ML),
                "MM" | "mm" => Ok(IsoCountryCode::MM),
                "MN" | "mn" => Ok(IsoCountryCode::MN),
                "MO" | "mo" => Ok(IsoCountryCode::MO),
                "MP" | "mp" => Ok(IsoCountryCode::MP),
                "MQ" | "mq" => Ok(IsoCountryCode::MQ),
                "MR" | "mr" => Ok(IsoCountryCode::MR),
                "MS" | "ms" => Ok(IsoCountryCode::MS),
                "MT" | "mt" => Ok(IsoCountryCode::MT),
                "MU" | "mu" => Ok(IsoCountryCode::MU),
                "MV" | "mv" => Ok(IsoCountryCode::MV),
                "MW" | "mw" => Ok(IsoCountryCode::MW),
                "MX" | "mx" => Ok(IsoCountryCode::MX),
                "MY" | "my" => Ok(IsoCountryCode::MY),
                "MZ" | "mz" => Ok(IsoCountryCode::MZ),
                "NA" | "na" => Ok(IsoCountryCode::NA),
                "NC" | "nc" => Ok(IsoCountryCode::NC),
                "NE" | "ne" => Ok(IsoCountryCode::NE),
                "NF" | "nf" => Ok(IsoCountryCode::NF),
                "NG" | "ng" => Ok(IsoCountryCode::NG),
                "NI" | "ni" => Ok(IsoCountryCode::NI),
                "NL" | "nl" => Ok(IsoCountryCode::NL),
                "NO" | "no" => Ok(IsoCountryCode::NO),
                "NP" | "np" => Ok(IsoCountryCode::NP),
                "NR" | "nr" => Ok(IsoCountryCode::NR),
                "NU" | "nu" => Ok(IsoCountryCode::NU),
                "NZ" | "nz" => Ok(IsoCountryCode::NZ),
                "OM" | "om" => Ok(IsoCountryCode::OM),
                "PA" | "pa" => Ok(IsoCountryCode::PA),
                "PE" | "pe" => Ok(IsoCountryCode::PE),
                "PF" | "pf" => Ok(IsoCountryCode::PF),
                "PG" | "pg" => Ok(IsoCountryCode::PG),
                "PH" | "ph" => Ok(IsoCountryCode::PH),
                "PK" | "pk" => Ok(IsoCountryCode::PK),
                "PL" | "pl" => Ok(IsoCountryCode::PL),
                "PM" | "pm" => Ok(IsoCountryCode::PM),
                "PN" | "pn" => Ok(IsoCountryCode::PN),
                "PR" | "pr" => Ok(IsoCountryCode::PR),
                "PS" | "ps" => Ok(IsoCountryCode::PS),
                "PT" | "pt" => Ok(IsoCountryCode::PT),
                "PW" | "pw" => Ok(IsoCountryCode::PW),
                "PY" | "py" => Ok(IsoCountryCode::PY),
                "QA" | "qa" => Ok(IsoCountryCode::QA),
                "RE" | "re" => Ok(IsoCountryCode::RE),
                "RO" | "ro" => Ok(IsoCountryCode::RO),
                "RS" | "rs" => Ok(IsoCountryCode::RS),
                "RU" | "ru" => Ok(IsoCountryCode::RU),
                "RW" | "rw" => Ok(IsoCountryCode::RW),
                "SA" | "sa" => Ok(IsoCountryCode::SA),
                "SB" | "sb" => Ok(IsoCountryCode::SB),
                "SC" | "sc" => Ok(IsoCountryCode::SC),
                "SD" | "sd" => Ok(IsoCountryCode::SD),
                "SS" | "ss" => Ok(IsoCountryCode::SS),
                "SE" | "se" => Ok(IsoCountryCode::SE),
                "SG" | "sg" => Ok(IsoCountryCode::SG),
                "SH" | "sh" => Ok(IsoCountryCode::SH),
                "SI" | "si" => Ok(IsoCountryCode::SI),
                "SJ" | "sj" => Ok(IsoCountryCode::SJ),
                "SK" | "sk" => Ok(IsoCountryCode::SK),
                "SL" | "sl" => Ok(IsoCountryCode::SL),
                "SM" | "sm" => Ok(IsoCountryCode::SM),
                "SN" | "sn" => Ok(IsoCountryCode::SN),
                "SO" | "so" => Ok(IsoCountryCode::SO),
                "SR" | "sr" => Ok(IsoCountryCode::SR),
                "ST" | "st" => Ok(IsoCountryCode::ST),
                "SV" | "sv" => Ok(IsoCountryCode::SV),
                "SX" | "sx" => Ok(IsoCountryCode::SX),
                "SY" | "sy" => Ok(IsoCountryCode::SY),
                "SZ" | "sz" => Ok(IsoCountryCode::SZ),
                "TC" | "tc" => Ok(IsoCountryCode::TC),
                "TD" | "td" => Ok(IsoCountryCode::TD),
                "TF" | "tf" => Ok(IsoCountryCode::TF),
                "TG" | "tg" => Ok(IsoCountryCode::TG),
                "TH" | "th" => Ok(IsoCountryCode::TH),
                "TJ" | "tj" => Ok(IsoCountryCode::TJ),
                "TK" | "tk" => Ok(IsoCountryCode::TK),
                "TL" | "tl" => Ok(IsoCountryCode::TL),
                "TM" | "tm" => Ok(IsoCountryCode::TM),
                "TN" | "tn" => Ok(IsoCountryCode::TN),
                "TO" | "to" => Ok(IsoCountryCode::TO),
                "TR" | "tr" => Ok(IsoCountryCode::TR),
                "TT" | "tt" => Ok(IsoCountryCode::TT),
                "TV" | "tv" => Ok(IsoCountryCode::TV),
                "TW" | "tw" => Ok(IsoCountryCode::TW),
                "TZ" | "tz" => Ok(IsoCountryCode::TZ),
                "UA" | "ua" => Ok(IsoCountryCode::UA),
                "UG" | "ug" => Ok(IsoCountryCode::UG),
                "UM" | "um" => Ok(IsoCountryCode::UM),
                "US" | "us" => Ok(IsoCountryCode::US),
                "UY" | "uy" => Ok(IsoCountryCode::UY),
                "UZ" | "uz" => Ok(IsoCountryCode::UZ),
                "VA" | "va" => Ok(IsoCountryCode::VA),
                "VC" | "vc" => Ok(IsoCountryCode::VC),
                "VE" | "ve" => Ok(IsoCountryCode::VE),
                "VG" | "vg" => Ok(IsoCountryCode::VG),
                "VI" | "vi" => Ok(IsoCountryCode::VI),
                "VN" | "vn" => Ok(IsoCountryCode::VN),
                "VU" | "vu" => Ok(IsoCountryCode::VU),
                "WF" | "wf" => Ok(IsoCountryCode::WF),
                "WS" | "ws" => Ok(IsoCountryCode::WS),
                "YE" | "ye" => Ok(IsoCountryCode::YE),
                "YT" | "yt" => Ok(IsoCountryCode::YT),
                "ZA" | "za" => Ok(IsoCountryCode::ZA),
                "ZM" | "zm" => Ok(IsoCountryCode::ZM),
                "ZW" | "zw" => Ok(IsoCountryCode::ZW),
                "CS" | "cs" => Ok(IsoCountryCode::CS),
                "AN" | "an" => Ok(IsoCountryCode::AN),
                _ => Err(()),
            },
            3 => match s {
                "AND" | "and" => Ok(IsoCountryCode::AD),
                "ARE" | "are" => Ok(IsoCountryCode::AE),
                "AFG" | "afg" => Ok(IsoCountryCode::AF),
                "ATG" | "atg" => Ok(IsoCountryCode::AG),
                "AIA" | "aia" => Ok(IsoCountryCode::AI),
                "ALB" | "alb" => Ok(IsoCountryCode::AL),
                "ARM" | "arm" => Ok(IsoCountryCode::AM),
                "AGO" | "ago" => Ok(IsoCountryCode::AO),
                "ATA" | "ata" => Ok(IsoCountryCode::AQ),
                "ARG" | "arg" => Ok(IsoCountryCode::AR),
                "ASM" | "asm" => Ok(IsoCountryCode::AS),
                "AUT" | "aut" => Ok(IsoCountryCode::AT),
                "AUS" | "aus" => Ok(IsoCountryCode::AU),
                "ABW" | "abw" => Ok(IsoCountryCode::AW),
                "ALA" | "ala" => Ok(IsoCountryCode::AX),
                "AZE" | "aze" => Ok(IsoCountryCode::AZ),
                "BIH" | "bih" => Ok(IsoCountryCode::BA),
                "BRB" | "brb" => Ok(IsoCountryCode::BB),
                "BGD" | "bgd" => Ok(IsoCountryCode::BD),
                "BEL" | "bel" => Ok(IsoCountryCode::BE),
                "BFA" | "bfa" => Ok(IsoCountryCode::BF),
                "BGR" | "bgr" => Ok(IsoCountryCode::BG),
                "BHR" | "bhr" => Ok(IsoCountryCode::BH),
                "BDI" | "bdi" => Ok(IsoCountryCode::BI),
                "BEN" | "ben" => Ok(IsoCountryCode::BJ),
                "BLM" | "blm" => Ok(IsoCountryCode::BL),
                "BMU" | "bmu" => Ok(IsoCountryCode::BM),
                "BRN" | "brn" => Ok(IsoCountryCode::BN),
                "BOL" | "bol" => Ok(IsoCountryCode::BO),
                "BES" | "bes" => Ok(IsoCountryCode::BQ),
                "BRA" | "bra" => Ok(IsoCountryCode::BR),
                "BHS" | "bhs" => Ok(IsoCountryCode::BS),
                "BTN" | "btn" => Ok(IsoCountryCode::BT),
                "BVT" | "bvt" => Ok(IsoCountryCode::BV),
                "BWA" | "bwa" => Ok(IsoCountryCode::BW),
                "BLR" | "blr" => Ok(IsoCountryCode::BY),
                "BLZ" | "blz" => Ok(IsoCountryCode::BZ),
                "CAN" | "can" => Ok(IsoCountryCode::CA),
                "CCK" | "cck" => Ok(IsoCountryCode::CC),
                "COD" | "cod" => Ok(IsoCountryCode::CD),
                "CAF" | "caf" => Ok(IsoCountryCode::CF),
                "COG" | "cog" => Ok(IsoCountryCode::CG),
                "CHE" | "che" => Ok(IsoCountryCode::CH),
                "CIV" | "civ" => Ok(IsoCountryCode::CI),
                "COK" | "cok" => Ok(IsoCountryCode::CK),
                "CHL" | "chl" => Ok(IsoCountryCode::CL),
                "CMR" | "cmr" => Ok(IsoCountryCode::CM),
                "CHN" | "chn" => Ok(IsoCountryCode::CN),
                "COL" | "col" => Ok(IsoCountryCode::CO),
                "CRI" | "cri" => Ok(IsoCountryCode::CR),
                "CUB" | "cub" => Ok(IsoCountryCode::CU),
                "CPV" | "cpv" => Ok(IsoCountryCode::CV),
                "CUW" | "cuw" => Ok(IsoCountryCode::CW),
                "CXR" | "cxr" => Ok(IsoCountryCode::CX),
                "CYP" | "cyp" => Ok(IsoCountryCode::CY),
                "CZE" | "cze" => Ok(IsoCountryCode::CZ),
                "DEU" | "deu" => Ok(IsoCountryCode::DE),
                "DJI" | "dji" => Ok(IsoCountryCode::DJ),
                "DNK" | "dnk" => Ok(IsoCountryCode::DK),
                "DMA" | "dma" => Ok(IsoCountryCode::DM),
                "DOM" | "dom" => Ok(IsoCountryCode::DO),
                "DZA" | "dza" => Ok(IsoCountryCode::DZ),
                "ECU" | "ecu" => Ok(IsoCountryCode::EC),
                "EST" | "est" => Ok(IsoCountryCode::EE),
                "EGY" | "egy" => Ok(IsoCountryCode::EG),
                "ESH" | "esh" => Ok(IsoCountryCode::EH),
                "ERI" | "eri" => Ok(IsoCountryCode::ER),
                "ESP" | "esp" => Ok(IsoCountryCode::ES),
                "ETH" | "eth" => Ok(IsoCountryCode::ET),
                "FIN" | "fin" => Ok(IsoCountryCode::FI),
                "FJI" | "fji" => Ok(IsoCountryCode::FJ),
                "FLK" | "flk" => Ok(IsoCountryCode::FK),
                "FSM" | "fsm" => Ok(IsoCountryCode::FM),
                "FRO" | "fro" => Ok(IsoCountryCode::FO),
                "FRA" | "fra" => Ok(IsoCountryCode::FR),
                "GAB" | "gab" => Ok(IsoCountryCode::GA),
                "GBR" | "gbr" => Ok(IsoCountryCode::GB),
                "GRD" | "grd" => Ok(IsoCountryCode::GD),
                "GEO" | "geo" => Ok(IsoCountryCode::GE),
                "GUF" | "guf" => Ok(IsoCountryCode::GF),
                "GGY" | "ggy" => Ok(IsoCountryCode::GG),
                "GHA" | "gha" => Ok(IsoCountryCode::GH),
                "GIB" | "gib" => Ok(IsoCountryCode::GI),
                "GRL" | "grl" => Ok(IsoCountryCode::GL),
                "GMB" | "gmb" => Ok(IsoCountryCode::GM),
                "GIN" | "gin" => Ok(IsoCountryCode::GN),
                "GLP" | "glp" => Ok(IsoCountryCode::GP),
                "GNQ" | "gnq" => Ok(IsoCountryCode::GQ),
                "GRC" | "grc" => Ok(IsoCountryCode::GR),
                "SGS" | "sgs" => Ok(IsoCountryCode::GS),
                "GTM" | "gtm" => Ok(IsoCountryCode::GT),
                "GUM" | "gum" => Ok(IsoCountryCode::GU),
                "GNB" | "gnb" => Ok(IsoCountryCode::GW),
                "GUY" | "guy" => Ok(IsoCountryCode::GY),
                "HKG" | "hkg" => Ok(IsoCountryCode::HK),
                "HMD" | "hmd" => Ok(IsoCountryCode::HM),
                "HND" | "hnd" => Ok(IsoCountryCode::HN),
                "HRV" | "hrv" => Ok(IsoCountryCode::HR),
                "HTI" | "hti" => Ok(IsoCountryCode::HT),
                "HUN" | "hun" => Ok(IsoCountryCode::HU),
                "IDN" | "idn" => Ok(IsoCountryCode::ID),
                "IRL" | "irl" => Ok(IsoCountryCode::IE),
                "ISR" | "isr" => Ok(IsoCountryCode::IL),
                "IMN" | "imn" => Ok(IsoCountryCode::IM),
                "IND" | "ind" => Ok(IsoCountryCode::IN),
                "IOT" | "iot" => Ok(IsoCountryCode::IO),
                "IRQ" | "irq" => Ok(IsoCountryCode::IQ),
                "IRN" | "irn" => Ok(IsoCountryCode::IR),
                "ISL" | "isl" => Ok(IsoCountryCode::IS),
                "ITA" | "ita" => Ok(IsoCountryCode::IT),
                "JEY" | "jey" => Ok(IsoCountryCode::JE),
                "JAM" | "jam" => Ok(IsoCountryCode::JM),
                "JOR" | "jor" => Ok(IsoCountryCode::JO),
                "JPN" | "jpn" => Ok(IsoCountryCode::JP),
                "KEN" | "ken" => Ok(IsoCountryCode::KE),
                "KGZ" | "kgz" => Ok(IsoCountryCode::KG),
                "KHM" | "khm" => Ok(IsoCountryCode::KH),
                "KIR" | "kir" => Ok(IsoCountryCode::KI),
                "COM" | "com" => Ok(IsoCountryCode::KM),
                "KNA" | "kna" => Ok(IsoCountryCode::KN),
                "PRK" | "prk" => Ok(IsoCountryCode::KP),
                "KOR" | "kor" => Ok(IsoCountryCode::KR),
                "XKX" | "xkx" => Ok(IsoCountryCode::XK),
                "KWT" | "kwt" => Ok(IsoCountryCode::KW),
                "CYM" | "cym" => Ok(IsoCountryCode::KY),
                "KAZ" | "kaz" => Ok(IsoCountryCode::KZ),
                "LAO" | "lao" => Ok(IsoCountryCode::LA),
                "LBN" | "lbn" => Ok(IsoCountryCode::LB),
                "LCA" | "lca" => Ok(IsoCountryCode::LC),
                "LIE" | "lie" => Ok(IsoCountryCode::LI),
                "LKA" | "lka" => Ok(IsoCountryCode::LK),
                "LBR" | "lbr" => Ok(IsoCountryCode::LR),
                "LSO" | "lso" => Ok(IsoCountryCode::LS),
                "LTU" | "ltu" => Ok(IsoCountryCode::LT),
                "LUX" | "lux" => Ok(IsoCountryCode::LU),
                "LVA" | "lva" => Ok(IsoCountryCode::LV),
                "LBY" | "lby" => Ok(IsoCountryCode::LY),
                "MAR" | "mar" => Ok(IsoCountryCode::MA),
                "MCO" | "mco" => Ok(IsoCountryCode::MC),
                "MDA" | "mda" => Ok(IsoCountryCode::MD),
                "MNE" | "mne" => Ok(IsoCountryCode::ME),
                "MAF" | "maf" => Ok(IsoCountryCode::MF),
                "MDG" | "mdg" => Ok(IsoCountryCode::MG),
                "MHL" | "mhl" => Ok(IsoCountryCode::MH),
                "MKD" | "mkd" => Ok(IsoCountryCode::MK),
                "MLI" | "mli" => Ok(IsoCountryCode::ML),
                "MMR" | "mmr" => Ok(IsoCountryCode::MM),
                "MNG" | "mng" => Ok(IsoCountryCode::MN),
                "MAC" | "mac" => Ok(IsoCountryCode::MO),
                "MNP" | "mnp" => Ok(IsoCountryCode::MP),
                "MTQ" | "mtq" => Ok(IsoCountryCode::MQ),
                "MRT" | "mrt" => Ok(IsoCountryCode::MR),
                "MSR" | "msr" => Ok(IsoCountryCode::MS),
                "MLT" | "mlt" => Ok(IsoCountryCode::MT),
                "MUS" | "mus" => Ok(IsoCountryCode::MU),
                "MDV" | "mdv" => Ok(IsoCountryCode::MV),
                "MWI" | "mwi" => Ok(IsoCountryCode::MW),
                "MEX" | "mex" => Ok(IsoCountryCode::MX),
                "MYS" | "mys" => Ok(IsoCountryCode::MY),
                "MOZ" | "moz" => Ok(IsoCountryCode::MZ),
                "NAM" | "nam" => Ok(IsoCountryCode::NA),
                "NCL" | "ncl" => Ok(IsoCountryCode::NC),
                "NER" | "ner" => Ok(IsoCountryCode::NE),
                "NFK" | "nfk" => Ok(IsoCountryCode::NF),
                "NGA" | "nga" => Ok(IsoCountryCode::NG),
                "NIC" | "nic" => Ok(IsoCountryCode::NI),
                "NLD" | "nld" => Ok(IsoCountryCode::NL),
                "NOR" | "nor" => Ok(IsoCountryCode::NO),
                "NPL" | "npl" => Ok(IsoCountryCode::NP),
                "NRU" | "nru" => Ok(IsoCountryCode::NR),
                "NIU" | "niu" => Ok(IsoCountryCode::NU),
                "NZL" | "nzl" => Ok(IsoCountryCode::NZ),
                "OMN" | "omn" => Ok(IsoCountryCode::OM),
                "PAN" | "pan" => Ok(IsoCountryCode::PA),
                "PER" | "per" => Ok(IsoCountryCode::PE),
                "PYF" | "pyf" => Ok(IsoCountryCode::PF),
                "PNG" | "png" => Ok(IsoCountryCode::PG),
                "PHL" | "phl" => Ok(IsoCountryCode::PH),
                "PAK" | "pak" => Ok(IsoCountryCode::PK),
                "POL" | "pol" => Ok(IsoCountryCode::PL),
                "SPM" | "spm" => Ok(IsoCountryCode::PM),
                "PCN" | "pcn" => Ok(IsoCountryCode::PN),
                "PRI" | "pri" => Ok(IsoCountryCode::PR),
                "PSE" | "pse" => Ok(IsoCountryCode::PS),
                "PRT" | "prt" => Ok(IsoCountryCode::PT),
                "PLW" | "plw" => Ok(IsoCountryCode::PW),
                "PRY" | "pry" => Ok(IsoCountryCode::PY),
                "QAT" | "qat" => Ok(IsoCountryCode::QA),
                "REU" | "reu" => Ok(IsoCountryCode::RE),
                "ROU" | "rou" => Ok(IsoCountryCode::RO),
                "SRB" | "srb" => Ok(IsoCountryCode::RS),
                "RUS" | "rus" => Ok(IsoCountryCode::RU),
                "RWA" | "rwa" => Ok(IsoCountryCode::RW),
                "SAU" | "sau" => Ok(IsoCountryCode::SA),
                "SLB" | "slb" => Ok(IsoCountryCode::SB),
                "SYC" | "syc" => Ok(IsoCountryCode::SC),
                "SDN" | "sdn" => Ok(IsoCountryCode::SD),
                "SSD" | "ssd" => Ok(IsoCountryCode::SS),
                "SWE" | "swe" => Ok(IsoCountryCode::SE),
                "SGP" | "sgp" => Ok(IsoCountryCode::SG),
                "SHN" | "shn" => Ok(IsoCountryCode::SH),
                "SVN" | "svn" => Ok(IsoCountryCode::SI),
                "SJM" | "sjm" => Ok(IsoCountryCode::SJ),
                "SVK" | "svk" => Ok(IsoCountryCode::SK),
                "SLE" | "sle" => Ok(IsoCountryCode::SL),
                "SMR" | "smr" => Ok(IsoCountryCode::SM),
                "SEN" | "sen" => Ok(IsoCountryCode::SN),
                "SOM" | "som" => Ok(IsoCountryCode::SO),
                "SUR" | "sur" => Ok(IsoCountryCode::SR),
                "STP" | "stp" => Ok(IsoCountryCode::ST),
                "SLV" | "slv" => Ok(IsoCountryCode::SV),
                "SXM" | "sxm" => Ok(IsoCountryCode::SX),
                "SYR" | "syr" => Ok(IsoCountryCode::SY),
                "SWZ" | "swz" => Ok(IsoCountryCode::SZ),
                "TCA" | "tca" => Ok(IsoCountryCode::TC),
                "TCD" | "tcd" => Ok(IsoCountryCode::TD),
                "ATF" | "atf" => Ok(IsoCountryCode::TF),
                "TGO" | "tgo" => Ok(IsoCountryCode::TG),
                "THA" | "tha" => Ok(IsoCountryCode::TH),
                "TJK" | "tjk" => Ok(IsoCountryCode::TJ),
                "TKL" | "tkl" => Ok(IsoCountryCode::TK),
                "TLS" | "tls" => Ok(IsoCountryCode::TL),
                "TKM" | "tkm" => Ok(IsoCountryCode::TM),
                "TUN" | "tun" => Ok(IsoCountryCode::TN),
                "TON" | "ton" => Ok(IsoCountryCode::TO),
                "TUR" | "tur" => Ok(IsoCountryCode::TR),
                "TTO" | "tto" => Ok(IsoCountryCode::TT),
                "TUV" | "tuv" => Ok(IsoCountryCode::TV),
                "TWN" | "twn" => Ok(IsoCountryCode::TW),
                "TZA" | "tza" => Ok(IsoCountryCode::TZ),
                "UKR" | "ukr" => Ok(IsoCountryCode::UA),
                "UGA" | "uga" => Ok(IsoCountryCode::UG),
                "UMI" | "umi" => Ok(IsoCountryCode::UM),
                "USA" | "usa" => Ok(IsoCountryCode::US),
                "URY" | "ury" => Ok(IsoCountryCode::UY),
                "UZB" | "uzb" => Ok(IsoCountryCode::UZ),
                "VAT" | "vat" => Ok(IsoCountryCode::VA),
                "VCT" | "vct" => Ok(IsoCountryCode::VC),
                "VEN" | "ven" => Ok(IsoCountryCode::VE),
                "VGB" | "vgb" => Ok(IsoCountryCode::VG),
                "VIR" | "vir" => Ok(IsoCountryCode::VI),
                "VNM" | "vnm" => Ok(IsoCountryCode::VN),
                "VUT" | "vut" => Ok(IsoCountryCode::VU),
                "WLF" | "wlf" => Ok(IsoCountryCode::WF),
                "WSM" | "wsm" => Ok(IsoCountryCode::WS),
                "YEM" | "yem" => Ok(IsoCountryCode::YE),
                "MYT" | "myt" => Ok(IsoCountryCode::YT),
                "ZAF" | "zaf" => Ok(IsoCountryCode::ZA),
                "ZMB" | "zmb" => Ok(IsoCountryCode::ZM),
                "ZWE" | "zwe" => Ok(IsoCountryCode::ZW),
                "SCG" | "scg" => Ok(IsoCountryCode::CS),
                "ANT" | "ant" => Ok(IsoCountryCode::AN),
                _ => Err(()),
            },
            _ => Err(()),
        }
    }
}
