name: Rust

on:
  push:
    branches: [ "ci-setup" ]
  pull_request:
    branches: [ "ci-setup" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install capnproto libssl-dev liblua5.4-dev
    - name: Build
      run: cargo build --all
    - name: Run tests
      run: cargo test --all

