name: Sphinx-Doc
permissions: { }

on:
  push:
    paths:
      - 'sphinx/**'
  pull_request:
    paths:
      - 'sphinx/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - g3proxy
          - g3tiles
    steps:
      - uses: actions/checkout@v4
      - uses: ammaraskar/sphinx-action@8b4f60114d7fd1faeba1a712269168508d4750d2 # 0.4
        with:
          docs-folder: "sphinx/${{ matrix.component }}"
