name: Sphinx-Doc

on:
  push:
    paths:
      - 'g3proxy/doc/**'
      - 'g3tiles/doc/**'
  pull_request:
    paths:
      - 'g3proxy/doc/**'
      - 'g3tiles/doc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - g3proxy
    steps:
      - uses: actions/checkout@v4
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "${{ matrix.component }}/doc/"
