name: Windows-CI
permissions: { }

on:
  push:
    paths-ignore:
      - 'ansible/**'
      - 'doc/**'
      - 'sphinx/**'
      - 'scripts/**'
    branches:
      - 'master'
      - 'lts/**'
  pull_request:
    branches:
      - 'master'
      - 'lts/**'

env:
  CARGO_TERM_COLOR: always
  VCPKG_ROOT: C:\vcpkg
  WIN_FEATURES: rustls-ring,quic,vendored-c-ares,hickory

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
        with:
          toolchain: stable
          components: clippy
      - name: Install tools (choco)
        run: choco install capnproto
      - name: Install lib dependencies (vcpkg)
        run: vcpkg install --triplet=x64-windows-static-md openssl
      - name: Cargo build
        run: cargo build --no-default-features --features $env:WIN_FEATURES
      - name: Cargo clippy
        run: cargo clippy --no-default-features --features $env:WIN_FEATURES --tests -- --deny warnings
      - name: Cargo test
        run: cargo test --no-default-features --features $env:WIN_FEATURES --workspace --exclude g3-journal

  build-vendored-g1:
    name: Build vendored
    runs-on: windows-latest
    strategy:
      matrix:
        feature:
          - vendored-openssl,rustls-ring
          - vendored-tongsuo,rustls-ring
          - vendored-boringssl,rustls-ring
        component:
          - g3proxy
          - g3bench
          - g3tiles
    steps:
      - name: Install common tools
        run: choco install capnproto
      - name: Install nasm and ninja for BoringSSL
        if: contains(matrix.feature, 'vendored-boringssl')
        run: choco install nasm ninja
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
        with:
          toolchain: stable
          components: clippy
      - name: Cargo build
        run: cargo build --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }}
      - name: Cargo clippy
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }} -- --deny warnings

  build-vendored-g2:
    name: Build vendored
    runs-on: windows-latest
    strategy:
      matrix:
        feature:
          - vendored-openssl
          - vendored-tongsuo
          - vendored-boringssl
        component:
          - g3fcgen
          - g3mkcert
          - g3keymess
    steps:
      - name: Install common tools
        run: choco install capnproto
      - name: Install nasm and ninja for BoringSSL
        if: contains(matrix.feature, 'vendored-boringssl')
        run: choco install nasm ninja
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
        with:
          toolchain: stable
          components: clippy
      - name: Cargo build
        run: cargo build --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }}
      - name: Cargo clippy
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }} -- --deny warnings
