name: Windows-CI

on:
  push:
    paths-ignore:
      - 'ansible/**'
      - 'doc/**'
      - 'demo/**'
      - 'scripts/**'
      - 'g3proxy/doc/**'
      - 'g3tiles/doc/**'
    branches:
      - 'master'
      - 'rel/**'
      - 'lts/**'
  pull_request:
    branches:
      - 'master'
      - 'rel/**'
      - 'lts/**'

env:
  CARGO_TERM_COLOR: always
  VCPKG_ROOT: C:\vcpkg
  WIN_FEATURES: quic,vendored-c-ares,hickory

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # v1
        with:
          toolchain: stable
          components: clippy
      - name: Install tools (choco)
        run: choco install capnproto
      - name: Install lib dependencies (vcpkg)
        run: vcpkg install --triplet=x64-windows-static-md openssl
      - name: Cargo build
        run: cargo build --no-default-features --features $env:WIN_FEATURES
      - name: Cargo clippy
        run: cargo clippy --no-default-features --features $env:WIN_FEATURES --tests
      - name: Cargo test
        run: cargo test --no-default-features --features $env:WIN_FEATURES

  build-vendored:
    name: Build vendored
    runs-on: windows-latest
    strategy:
      matrix:
        feature:
          - vendored-openssl
          - vendored-tongsuo
          - vendored-aws-lc
          - vendored-boringssl
        component:
          - g3proxy
    steps:
      - name: Install common tools
        run: choco install capnproto
      - name: Install nasm and ninja for BoringSSL
        if: matrix.feature == 'vendored-boringssl'
        run: choco install nasm ninja
      - name: Install nasm for AWS-LC
        if: matrix.feature == 'vendored-aws-lc'
        uses: ilammy/setup-nasm@v1
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # v1
        with:
          toolchain: stable
          components: clippy
      - name: Cargo build
        run: cargo build --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }}
      - name: Cargo clippy
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }}
